---

webhost:
  nginx_installation_type: "source"
  nginx_module_fancy_index: False
  nginx_create_blank_index: True
  webroot: /usr/share/nginx/html

  nginx_sites:
    00_default:
      - listen 80 default_server
      - server_name _
      - root "/usr/share/nginx/html"
      - index index.html
      - autoindex on

nas:
  something:

pi:
  hole:

terminal: "xterm-256color"
terminal_alt: "xterm-256color"

wm: shell
browser: "w3m"
