---

- block:

    - name: Install font packages
      aur:
        use: paru
        name: "{{ theme.packages.fonts }}"
        state: present
      become: False
      when: ansible_distribution == 'Archlinux'

  tags: ['packages']

- name: Ensure /usr/local/share fonts exists
  file:
    path: /usr/local/share/fonts
    state: directory
    owner: root
    group: root
    recurse: True

- name: Extract fonts to /usr/local/share/fonts
  unarchive:
    src: usr/local/share/fonts.tar.xz
    dest: "/usr/local/share/fonts"

# - name: Install fonts.conf
#   copy:
#     src: home/.config/fontconfig/fonts.conf
#     dest: "{{ user.home }}/.config/fontconfig/fonts.conf"
#     owner: "{{ user.name }}"
#     group: "{{ user.group }}"
#     mode: '0644'
#     backup: yes
#   tags: ['fonts']
#
- name: Update font-cache
  command: fc-cache -fv
  register: font_cache
  changed_when: font_cache.rc != 0
