---
# tasks file for theme

- name: Starting theme tasks
  debug:
    msg: "Starting theme tasks!"

- name: Group packages to install
  set_fact:
    packagesTheme: "{{ packages.icons + packages.cursors + packages.gtk3 + packages.qt5 + packages.qt6 + packages.kvantum + packages.fonts }}"
  tags: ['packages','theme']

- name: Install theme group packages
  aur:
    use: paru
    name: "{{ packagesTheme | flatten(1) }}"
    state: present
  become: False
  when: ansible_distribution == 'Archlinux'
  tags: ['packages','theme']

- name: Ensure theme directories exist
  file:
    dest: "{{ theme_directory_default_location }}/{{ item.dest }}"
    state: directory
    owner: "{{ item.owner | default(theme_directory_default_owner) }}"
    group: "{{ item.group | default(theme_directory_default_group) }}"
    mode: "{{ item.mode | default(theme_directory_default_mode) }}"
    recurse: "{{ item.recurse | default(theme_directory_default_recurse) }}"
  with_items: "{{ theme_directory_definitions }}"
  check_mode: no
  tags: ['profile']

- import_tasks:
    file: fonts.yml
  tags: ['fonts','theme']

- import_tasks:
    file: icons.yml
  tags: ['icons','theme']

- name: Ensure /usr/local/share themes exists
  file:
    path: /usr/local/share/themes
    state: directory
    owner: root
    group: root
    recurse: True
  tags: ['theme']

- name: Extract themes into /usr/local/share/themes
  unarchive:
    src: "usr/local/share/themes/{{ item }}"
    dest: "/usr/local/share/themes"
  with_items:
   - oomox-soundbot.tar.xz
   - ArchLabs-Dark.tar.gz
   - ArchLabs-Light.tar.gz
  tags: ['theme']

- name: Install gtk configurations
  template:
    src: "etc/skel/{{ item }}.j2"
    dest: "/etc/skel/{{ item }}"
    owner: root
    group: root
    mode: '0644'
    backup: yes
  with_items:
    - '.config/gtk-3.0/bookmarks'
    - '.config/gtk-3.0/gtk.css'
    - '.config/gtk-3.0/settings.ini'
    - '.config/gtk-4.0/settings.ini'
    - '.gtkrc-2.0'
  tags: ['profile', 'gtk']

- name: Install qt configurations
  template:
    src: "etc/skel/{{ item }}.j2"
    dest: "/etc/skel/{{ item }}"
    owner: root
    group: root
    mode: '0644'
    backup: yes
  with_items:
    - '.config/Kvantum/kvantum.kvconfig'
    - '.config/qt5ct/colors/syncopated.conf'
    - '.config/qt5ct/qt5ct.conf'
    - '.config/qt6ct/colors/syncopated.conf'
    - '.config/qt6ct/qt6ct.conf'
  tags: ['profile', 'qt']

- name: Create syncopated backgrounds folder
  file:
    path: /usr/share/backgrounds/syncopated
    state: directory
    mode: '0755'
    group: "{{ user.group }}"

- name: Install backgrounds
  synchronize:
    src: "usr/share/backgrounds/syncopated/"
    dest: "/usr/share/backgrounds/syncopated/"
    recursive: yes
    mode: push
    delete: no
    rsync_opts:
      - "--update"
      - "--backup"
      - "--suffix={{ suffix }}"
  tags: ['backgrounds']
