---
# tasks file for shell

- name: Set user shell
  user:
    name: "{{ item }}"
    shell: "{{ user.shell }}"
  with_items:
    - "{{ user.name }}"
    - root
  tags: ['profile']

- name: Import bash role
  import_role:
    name: bash
  tags: ['bash', 'profile']

- name: Import zsh role
  import_role:
    name: zsh
  tags: ['zsh', 'profile']
