---
# tasks file for zsh

- name: ZSH Tasks
  debug:
    msg: "Starting zsh tasks"

- name: Install zsh
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - zsh
    - zoxide
  tags: ['packages']

- name: Install oh-my-zsh
  shell: |
    if [ ! -d "/usr/local/share/oh-my-zsh" ]; then
      export ZSH="/usr/local/share/oh-my-zsh"
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    fi
  tags: ['ohmyzsh']

- name: Install zsh custom functions
  synchronize:
    src: home/.local/share/zsh
    dest: "{{ user.home }}/.local/share/"
    recursive: yes
    mode: push
    delete: no
    checksum: yes
    perms: no
    owner: False
    group: False
    rsync_opts:
      - "--update"
      - "--omit-dir-times"
      - "--progress"
      - "--itemize-changes"
  ignore_errors: "{{ ansible_check_mode }}"
  tags: ['env', 'profile']

# - name: Set permissions on zsh cutom function folder
#   file:
#     path: /usr/local/share/zsh
#     state: directory
#     owner: root
#     group: root
#     recurse: True

- name: Set zsh profile configs
  template:
    src: "home/{{ item }}.j2"
    dest: "{{ user.home }}/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: True
  with_items:
    - .aliases
    - .zprofile
    - .zshenv
    - .zshrc
    - .zlogin
  tags: ['env', 'profile']
