---
# tasks file for bash

- name: Copy bashrc and bash_logout to /etc/skel
  copy:
    src: "etc/skel/{{ item }}"
    dest: "{{ user.home }}/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: True
  with_items:
    - .bashrc
    - .bash_logout
  when: user.shell == 'bash'
