---
# tasks file for bash

- name: Copy bashrc and bash_logout to /etc/skel
  copy:
    src: "etc/skel/{{ item }}"
    dest: "/etc/skel/{{ item }}"
    owner: root
    group: root
    mode: '0644'
    backup: True
  with_items:
    - .bashrc
    - .bash_logout
