---
# defaults file for flowise

flowise:
  repo: https://github.com/FlowiseAI/Flowise.git
  version: flowise@1.8.2
  path: "{{ user.home }}/LLMOS/flowise"
  image: flowiseai/flowise
  container_name: flowise
  volumes:
    - host: "{{ user.home }}/LLMOS/flowise/docker/data"
      container: /root/.flowise
    - host: "{{ user.home }}/LLMOS/flowise/docker/data/output"
      container: /root/.flowise/output
  ports:
    - host: 3002
      container: 3002
env:
  vars:
    port: 3002
    # cors_origins: "*"
    # iframe_origins: ""
    database_path: /root/.flowise
    apikey_path: /root/.flowise
    secretkey_path: /root/.flowise
    log_path: /root/.flowise/logs
    # number_of_proxies:  1
    # database_type: postgres
    # database_port: ""
    # database_host: ""
    # database_name: "flowise"
    # database_user: ""
    # database_password: ""
    # flowise_username: user
    # flowise_password: 1234
    # flowise_file_size_limit:
    # flowise_secretkey_overwrite: myencryptionkey
    debug: true
    # (error | warn | info | verbose | debug)
    log_level: debug

compose:
  entrypoint: /bin/sh -c "sleep 3; flowise start"
