---
# tasks file for user

- name: Include distro vars
  include_vars:
    file: vars/{{ ansible_distribution }}.yml
  tags: ['always']

- name: Set user shell
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
  with_items: "{{ users }}"
  tags: ['profile']

- name: Install .aliases and .profile
  copy:
    src: "etc/skel/{{ item }}"
    dest: "/etc/skel/{{ item }}"
    owner: root
    group: root
    mode: '0644'
    backup: True
  with_items:
    - .aliases
    - .profile
  tags: ['profile']

- name: Sync /etc/skel with users home
  synchronize:
    src: /etc/skel/
    dest: "{{ item.home }}/"
    recursive: yes
    mode: push
    delete: no
    checksum: yes
    perms: no
    rsync_opts:
      - "--update"
      - "--exclude='*.*~'"
      - "--omit-dir-times"
      - "--chown={{ item.name }}:{{ item.group }}"
      - "--backup"
      - "--suffix={{ suffix }}"
  with_items: "{{ users }}"
  when: item.name != 'root'
  delegate_to: "{{ inventory_hostname }}"
  tags: ['profile']
