---
# tasks file for user

- name: Starting user tasks
  debug:
    msg: "Starting user tasks"

- name: Include distro vars
  include_vars:
    file: vars/{{ ansible_distribution }}.yml
  tags: ['always']

- name: Set user shell
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
  with_items: "{{ users }}"
  tags: ['profile']

- name:  Install .aliases and .profile
  template:
    src: "etc/skel/{{ item }}.j2"
    dest: "/etc/skel/{{ item }}"
    owner: root
    group: root
    mode: '0644'
    backup: True
  with_items:
    - .aliases
    - .profile
  tags: ['profile']

- name: Install htop and lnav configs
  template:
    src: "etc/skel/.config/{{ item[1] }}.j2"
    dest: "{{ item[0] }}/{{ item[1] }}"
    owner: root
    group: root
    mode: '0644'
    backup: yes
  with_nested:
    - [ '/root/.config', '/etc/skel/.config' ]
    - [ 'htop/htoprc', 'lnav/checklog.lnav' ]
  tags: ['profile']

- name: Sync /etc/skel with users home
  synchronize:
    src: /etc/skel/
    dest: "{{ user.home }}/"
    recursive: yes
    mode: push
    delete: no
    checksum: yes
    perms: no
    rsync_opts:
      - "--update"
      - "--progress"
      - "--itemize-changes"
      - "--exclude='*.*~'"
      - "--omit-dir-times"
      - "--chown={{ user.name }}:{{ user.group }}"
      - "--backup"
      - "--suffix={{ suffix }}"
  delegate_to: "{{ inventory_hostname }}"
  tags: ['profile']
