---
# tasks file for user

- name: User Tasks
  debug:
    msg: "Starting user tasks"

# dotfiles

- import_tasks:
    file: autologin.yml
  tags: ['autologin']
  when: autologin|default(false)|bool == True
