---

- name: Create getty@tty1.service.d directory
  file:
    path: "/etc/systemd/system/getty@tty1.service.d"
    state: directory
    owner: root
    group: root

- name: Create systemd drop-in file for virtual console autologin
  template:
    src: "etc/systemd/system/getty@tty1.service.d/autologin.conf.j2"
    dest: "/etc/systemd/system/getty@tty1.service.d/autologin.conf"
    owner: root
    group: root
    mode: '0644'
    backup: yes
