---

- name: Sync input-remapper presets folder
  synchronize:
    src: home/.config/input-remapper-2/presets/
    dest: "{{ user.home }}/.config/input-remapper-2/presets/"
    recursive: yes
    mode: push
    delete: no
    checksum: yes
    perms: no
    rsync_opts:
      - "--update"
      - "--omit-dir-times"
      - "--progress"
      - "--itemize-changes"
      - "--chown={{ user.name }}:{{ user.group }}"
