---
# tasks file for desktop
- name: Collect only selected facts
  setup:
    filter:
      - 'ansible_processor'

- name: Desktop Tasks
  debug:
    msg: "Starting desktop tasks"
  register: expected_value

- name: Ensure desktop directories exist
  file:
    dest: "{{ desktop_directory_default_location }}/{{ item.dest }}"
    state: directory
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    recurse: "{{ item.recurse | default(false) }}"
  loop: "{{ desktop_directory_definitions }}"
  check_mode: no

- import_tasks:
    file: "theme.yml"
  tags: ['theme']

- import_tasks:
    file: "thunar.yml"
  tags: ['thunar']

# if this file does not exist, lightdm will fail to start
- name: Set dmrc to selected window manager
  copy:
    content: |
      [Desktop]
      Session={{wm}}
    dest: "{{ user.home }}/.dmrc"
    owner: "{{ user.name }}"
    mode: '0644'

#TODO: Add dunst and picom xdg autostart desktop entries
- name: Set dunst config
  template:
    src: "home/.config/dunst/dunstrc.j2"
    dest: "{{ user.home }}/.config/dunst/dunstrc"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  tags: ["profile", "dunst"]

- name: Set picom config
  template:
    src: "home/.config/picom.conf.j2"
    dest: "{{ user.home }}/.config/picom.conf"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  tags: ["profile", "picom"]
