---
# tasks file for desktop

- name: Install setuptools module
  pip:
    name: setuptools
    executable: pip
    state: present
    extra_args: --break-system-packages
  tags: ['packages', 'python']

- import_tasks:
    file: autologin.yml
  tags: ['autologin']
  when: autologin|default(false)|bool == True

- name: Import xorg role
  import_role:
    name: xorg
  tags: ['xorg']
  when: desktop.wm == 'i3'

- name: Import i3 role
  import_role:
    name: i3
  tags: ['i3']
  when: desktop.wm == 'i3'

- name: Import sway role
  import_role:
    name: sway
  tags: ['sway']
  when: desktop.wm == 'sway'

- name: Import gnome role
  import_role:
    name: gnome
  tags: ['gnome']
  when: desktop.wm == 'gnome'

# if this file does not exist, lightdm will fail to start
- name: Set dmrc to selected window manager
  copy:
    content: |
      [Desktop]
      Session={{ desktop.wm }}
    dest: "{{ user.home }}/.dmrc"
    owner: "{{ user.name }}"
    mode: '0644'

# - import_tasks:
#     file: swhkd.yml
#   tags: ['swhkd', 'keybindings']

- import_tasks:
    file: sxhkd.yml
  tags: ['sxhkd', 'keybindings']

# - import_tasks:
#     file: inputRemapper.yml
#   tags: ['inputRemapper', 'keybindings']

#TODO: Add dunst and picom xdg autostart desktop entries
- name: Set dunst config
  template:
    src: "etc/skel/.config/dunst/dunstrc.j2"
    dest: "/etc/skel/.config/dunst/dunstrc"
    owner: root
    group: root
    mode: "0644"
    backup: yes
  tags: ["profile", "dunst"]

- name: Set picom config
  template:
    src: "etc/skel/.config/picom/picom.conf.j2"
    dest: "/etc/skel/.config/picom/picom.conf"
    owner: root
    group: root
    mode: "0644"
    backup: yes
  tags: ["profile", "picom"]

- name: Set barrier server config
  copy:
    src: home/.config/Debauchee/soundbot.conf
    dest: "{{ user.home }}/.config/Debauchee/soundbot.conf"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  when: desktop.barrier.server is defined

- name: Set barrier server autostart
  template:
    src: "home/.config/autostart/barrier-server.desktop.j2"
    dest: "{{ user.home }}/.config/autostart/barrier-server.desktop"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: True
  when: desktop.barrier.server is defined

- name: Set barrier client autostart
  template:
    src: "home/.config/autostart/barrier-client.desktop.j2"
    dest: "{{ user.home }}/.config/autostart/barrier-client.desktop"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: True
  when: desktop.barrier.client is defined

- name: Set xdg autostart applications
  synchronize:
    src: etc/xdg/autostart/
    dest: /etc/xdg/autostart/
    recursive: yes
    mode: push
    delete: yes
    checksum: yes
    perms: no
    rsync_opts:
      - "--update"
      - "--progress"
      - "--itemize-changes"
      - "--exclude='*.*~'"
      - "--omit-dir-times"
      - "--chown=root:root"
      - "--backup"
      - "--suffix={{ suffix }}"

# - name: Remove xdg autostart entry
#   file:
#     path: "/etc/xdg/autostart/{{ item }}"
#     state: absent
#   with_items:
#     - picom.desktop
#     - autorandr-kde.desktop
#     - autorandr.desktop
#     - firewall-applet.desktop
#     - gnome-keyring-pkcs11.desktop
#     - gnome-keyring-secrets.desktop
#     - gnome-keyring-ssh.desktop
#     - polkit-kde-authentication-agent-1.desktop
#     - pamac-tray-budgie.desktop
#     - pamac-tray.desktop
#     - pulseaudio.desktop
#   tags: ["profile", "picom", "xdg"]
