---
# tasks file for desktop
- name: Collect only selected facts
  setup:
    filter:
      - 'ansible_processor'

- name: Desktop Tasks
  debug:
    msg: "Starting desktop tasks"
  register: expected_value

# - name: test expected_value
#   debug:
#     msg: "{{ expected_value }}"
#   tags: ['testing']

- name: Ensure desktop directories exist
  file:
    dest: "{{ desktop_directory_default_location }}/{{ item.dest }}"
    state: directory
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    recurse: "{{ item.recurse | default(false) }}"
  loop: "{{ desktop_directory_definitions }}"
  check_mode: no

- block:
    - name: Install desktop packages
      aur:
        use: paru
        name: "{{ packages.desktop }}"
        state: present
        extra_args: --overwrite '*'

    - name: Install browser packages
      aur:
        use: paru
        name: "{{ packages.browser }}"
        state: present
        extra_args: --overwrite '*'

    - name: Install media packages
      aur:
        use: paru
        name: "{{ packages.media }}"
        state: present
        extra_args: --overwrite '*'

    - name: Install development packages
      aur:
        use: paru
        name: "{{ packages.development }}"
        state: present
        extra_args: --overwrite '*'

    - name: Install texlive packages
      aur:
        use: paru
        name: "{{ packages.texlive }}"
        state: present
        extra_args: --overwrite '*'
      when: pkgs__texlive|default(false)|bool == True
      tags: ['texlive']

    - name: Install python packages
      aur:
        use: paru
        name: "{{ packages.python }}"
        state: present
        extra_args: --overwrite '*'

    - name: Install utility packages
      aur:
        use: paru
        name: "{{ packages.utility }}"
        state: present
        extra_args: --overwrite '*'

  become: False
  tags: ['packages']

#NOTETHIS: these can be used in a seperate playbook
# - name: Import sway role
#   import_role:
#     name: sway
#   tags: ['sway']
#   when: wm == 'sway'
#
# - name: Import gnome role
#   import_role:
#     name: gnome
#   tags: ['gnome']
#   when: wm == 'gnome'

# if this file does not exist, lightdm will fail to start
- name: Set dmrc to selected window manager
  copy:
    content: |
      [Desktop]
      Session={{wm }}
    dest: "{{ user.home }}/.dmrc"
    owner: "{{ user.name }}"
    mode: '0644'

- import_tasks:
    file: input-remapper.yml
  tags: ['input-remapper', 'keybindings']

- import_tasks:
    file: menu.yml
  tags: ['menu']

#TODO: Add dunst and picom xdg autostart desktop entries
- name: Set dunst config
  template:
    src: "home/.config/dunst/dunstrc.j2"
    dest: "{{ user.home }}/.config/dunst/dunstrc"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  tags: ["profile", "dunst"]

- name: Set picom config
  template:
    src: "home/.config/picom.conf.j2"
    dest: "{{ user.home }}/.config/picom.conf"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  tags: ["profile", "picom"]

- name: Set redshift config
  copy:
    src: home/.config/redshift/redshift.conf
    dest: "{{ user.home }}/.config/redshift/redshift.conf"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: False
  tags: ['redshift']

- import_tasks:
    file: barrier.yml
  tags: ['barrier']

- name: Install Thunar actions
  copy:
    src: "home/.config/Thunar/{{ item }}"
    dest: "{{ user.home }}/.config/Thunar/{{ item }}"
    mode: '0644'
    backup: yes
  with_items:
    - accels.scm
    - uca.xml
  tags: ['thunar']

- name: Set Thunar as default for opening directories
  shell: xdg-mime default thunar.desktop inode/directory
  become_user: "{{ user.name }}"
  tags: ['thunar']

- name: Set JackTrip autostart entry
  template:
    src: home/.config/autostart/JackTrip.desktop.j2
    dest: "{{ user.home }}/.config/autostart/JackTrip.desktop"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0644"
    backup: yes
    validate: "dex -d %s"
  when: jacktrip.server.args != '' or jacktrip.client.args != ''

- name: Set xdg autostart applications
  synchronize:
    src: etc/xdg/autostart/
    dest: /etc/xdg/autostart/
    recursive: yes
    mode: push
    delete: yes
    checksum: yes
    perms: no
    rsync_opts:
      - "--delete"
      - "--update"
      - "--progress"
      - "--itemize-changes"
      - "--exclude='*.*~'"
      - "--omit-dir-times"
      - "--chown=root:root"

- name: Update desktop database
  command: bash -lc "update-desktop-database"
