---
# tasks file for desktop
- name: Collect only selected facts
  setup:
    filter:
      - 'ansible_processor'

- name: Desktop Tasks
  debug:
    msg: "Starting desktop tasks"
  register: expected_value

- name: Ensure desktop directories exist
  file:
    dest: "{{ desktop_directory_default_location }}/{{ item.dest }}"
    state: directory
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    recurse: "{{ item.recurse | default(false) }}"
  loop: "{{ desktop_directory_definitions }}"
  check_mode: no

- import_tasks:
    file: "terminal.yml"
  tags: ['terminal']

- import_tasks:
    file: "x11.yml"
  tags: ['x11']

- import_tasks:
    file: "sxhkd.yml"
  tags: ['sxhkd']

- import_tasks:
    file: "i3.yml"
  tags: ['i3']

- import_tasks:
    file: input-remapper.yml
  tags: ['input-remapper', 'keybindings']

- import_tasks:
    file: menu.yml
  tags: ['menu']

- import_tasks:
    file: "theme.yml"
  tags: ['theme']

- import_tasks:
    file: "thunar.yml"
  tags: ['thunar']

# if this file does not exist, lightdm will fail to start
- name: Set dmrc to selected window manager
  copy:
    content: |
      [Desktop]
      Session={{wm}}
    dest: "{{ user.home }}/.dmrc"
    owner: "{{ user.name }}"
    mode: '0644'

#TODO: Add dunst and picom xdg autostart desktop entries
- name: Set dunst config
  template:
    src: "home/.config/dunst/dunstrc.j2"
    dest: "{{ user.home }}/.config/dunst/dunstrc"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  tags: ["profile", "dunst"]

- name: Set picom config
  template:
    src: "home/.config/picom.conf.j2"
    dest: "{{ user.home }}/.config/picom.conf"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  tags: ["profile", "picom"]

- name: Set redshift config
  copy:
    src: home/.config/redshift/redshift.conf
    dest: "{{ user.home }}/.config/redshift/redshift.conf"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: False
  tags: ['redshift']

- name: Set xdg autostart applications
  synchronize:
    src: etc/xdg/autostart/
    dest: /etc/xdg/autostart/
    recursive: yes
    mode: push
    delete: yes
    checksum: yes
    perms: no
    rsync_opts:
      - "--delete"
      - "--update"
      - "--progress"
      - "--itemize-changes"
      - "--exclude='*.*~'"
      - "--omit-dir-times"
      - "--chown=root:root"

- name: Update desktop database
  command: bash -lc "update-desktop-database"
