---

- import_tasks:
    file: xdg.yml
  tags: ['xdg']

- name: Synchronize templates - rofi
  template:
    src: "etc/skel/{{ item }}.j2"
    dest: "/etc/skel/{{ item }}"
    owner: root
    group: root
    mode: preserve
    backup: yes
  with_items:
    - .config/rofi/config.rasi
    - .config/rofi/gruvbox-common.rasi
    - .config/rofi/gruvbox-dark-hard.rasi
    - .config/rofi/colors/onedark.rasi
    - .config/rofi/scripts/launcher_main.sh
    - .config/rofi/scripts/launcher_t1.sh
    - .config/rofi/scripts/launcher_t4.sh
    - .config/rofi/launchers/type-1/shared/colors.rasi
    - .config/rofi/launchers/type-1/shared/fonts.rasi
    - .config/rofi/launchers/type-1/style-8.rasi
    - .config/rofi/launchers/type-1/style-10.rasi
    - .config/rofi/launchers/type-4/shared/colors.rasi
    - .config/rofi/launchers/type-4/shared/fonts.rasi
    - .config/rofi/launchers/type-4/style-6.rasi
  tags: ['profile', 'rofi']
