---

- name: Create /etc/xdg/menus and /usr/share/desktop-entries
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /etc/xdg/menus
    - /etc/xdg/menus/applications-merged
    - /etc/xdg/Thunar
    - /usr/share/desktop-directories
