---

- name: install swhkd
  aur:
    use: auto
    name: swhkd
    state: present
  become: False
  tags: ['packages']

# - name: Install hotkeys service file
#   copy:
#     src: "usr/lib/systemd/user/hotkeys.service"
#     dest: "/usr/lib/systemd/user/hotkeys.service"
#     mode: '0644'

- name: Install hotkeys.sh
  copy:
    src: usr/local/bin/hotkeys.sh
    dest: /usr/local/bin/hotkeys.sh
    owner: root
    group: root
    mode: '0755'
    backup: True

- name: Install swhkd keybindings
  template:
    src: "etc/skel/.config/swhkd/swhkdrc.j2"
    dest: "{{ user.home }}/.config/swhkd/swhkdrc"
    owner: root
    group: root
    mode: "0644"
    backup: yes
  register: keybindings
  tags: ["profile"]

# - name: enable hotkeys services
#   systemd:
#     name: hotkeys
#     enabled: yes
#     scope: user
#     daemon_reload: yes
#   environment:
#     XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
#   become: False
#   ignore_errors: "{{ ansible_check_mode }}"
