---

- name: Install pulseaudio packages
  shell: "{{ package_install_command }} {{ pulseaudio.packages|join(' ') }}"
  become: False
  tags: ['packages']

- name: Update pulseaudio configs
  copy:
    src: "etc/pulse/{{ item }}"
    dest: "{{ user.home }}/.config/pulse/{{ item }}"
    owner: root
    group: root
    mode: '0644'
    backup: yes
  with_items:
    - client.conf
    - daemon.conf
    - default.pa
    - system.pa

- block:

    - block:
        - name: install bluetooth packages
          aur:
            use: auto
            name: "{{ item }}"
            state: present
          with_items:
            - pulseaudio-bluetooth
          become: False

      tags: ['packages']

    - name: Ensure default.pa.d exists
      file:
        path: /etc/pulse/default.pa.d
        state: directory

    - name: Install pulseaudio bluetooth config
      copy:
        src: etc/pulse/default.pa.d/bluetooth.pa
        dest: /etc/pulse/default.pa.d/bluetooth.pa
        mode: '0644'

    - name: Enabled bluetooth service
      service:
        name: bluetooth
        state: started
        enabled: True

  when: use_bluetooth|bool
  notify: restart pulseaudio
  tags: ['bluetooth']

# - name: Adjust pulseaudio.service file
#   lineinfile:
#     path: /usr/lib/systemd/user/pulseaudio.service
#     insertafter: '^Description'
#     line: 'After=jack_control.service'
#     backup: yes

# - name: enable pulseaudio service
#   systemd:
#     name: "{{ item }}"
#     enabled: yes
#     scope: user
#   with_items:
#     - pulseaudio.service
#     - pulseaudio.socket
#   environment:
#     XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
#   become_user: "{{ user.name }}"
