---
# tasks file for pulseaudio

- name: Include distro vars
  include_vars:
    file: vars/{{ ansible_distribution }}.yml
  tags: ['always']

- name: Starting pulseaudio tasks
  debug:
    msg: "Starting pulseaudio tasks"
