---
# tasks file for pulseaudio

- name: Pulseaudio Tasks
  debug:
    msg: "Starting pulseaudio tasks"

- name: Install pulseaudio packages
  aur:
    use: paru
    name: "{{ packages.pulseaudio }}"
    state: present
  become: False
  tags: ['packages']

- name: Ensure pulseaudio directories exist
  file:
    dest: "{{ pulse_directory_default_location }}/{{ item.dest }}"
    state: directory
    owner: "{{ item.owner | default(pulse_directory_default_owner) }}"
    group: "{{ item.group | default(pulse_directory_default_group) }}"
    mode: "{{ item.mode | default(pulse_directory_default_mode) }}"
    recurse: "{{ item.recurse | default(pulse_directory_default_recurse) }}"
  with_items: "{{ pulse_directory_definitions }}"
  check_mode: no
  tags: ["profile"]

- name: Update pulseaudio configs
  copy:
    src: "etc/pulse/{{ item }}"
    dest: "{{ user.home }}/.config/pulse/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0644"
    backup: yes
  with_items:
    - client.conf
    - daemon.conf
    - default.pa
    - system.pa

- block:
    - block:
        - name: Install bluetooth packages
          aur:
            use: auto
            name: "{{ item }}"
            state: present
          with_items:
            - bluetooth-autoconnect
            - bluez
            - bluez-utils
            - pulseaudio-bluetooth
          become: False
          when: ansible_distribution == 'Archlinux'

      tags: ["packages"]

    - name: Ensure default.pa.d exists
      file:
        path: /etc/pulse/default.pa.d
        state: directory

    - name: Install pulseaudio bluetooth config
      copy:
        src: etc/pulse/default.pa.d/bluetooth.pa
        dest: /etc/pulse/default.pa.d/bluetooth.pa
        mode: "0644"

  when: bluetooth|bool
  notify: restart pulseaudio
  tags: ["bluetooth"]
# - name: Adjust pulseaudio.service file
#   lineinfile:
#     path: /usr/lib/systemd/user/pulseaudio.service
#     insertafter: '^Description'
#     line: 'After=jack_control.service'
#     backup: yes

# - name: enable pulseaudio service
#   systemd:
#     name: "{{ item }}"
#     enabled: yes
#     scope: user
#   with_items:
#     - pulseaudio.service
#     - pulseaudio.socket
#   environment:
#     XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
#   become_user: "{{ user.name }}"
