---

- block:
    - name: Stop pulseaudio service
      systemd:
        name: "{{ item }}"
        state: stopped
        scope: user
      with_items:
        - pulseaudio.service
        - pulseaudio.socket
      environment:
        XDG_RUNTIME_DIR: "/run/user/1000"
      register: servicestat
      failed_when: "not 'Could not find the requested service' in servicestat.msg and servicestat.rc != 0"
      ignore_errors: "{{ ansible_check_mode }}"

    # - name: Uninstall pulseaudio packages
    #   aur:
    #     use: paru
    #     name: "{{ packages.pulseaudio }}"
    #     state: absent

  become: False
