---

- name: stop pulseaudio service
  systemd:
    name: "{{ item }}"
    state: stopped
    scope: user
  with_items:
    - pulseaudio.service
    - pulseaudio.socket
  environment:
    XDG_RUNTIME_DIR: "/run/user/1000"
  become: False
  register: servicestat
  failed_when: "not 'Could not find the requested service' in servicestat.msg and servicestat.rc != 0"
  
- name: Uninstall pulseaudio packages
  shell: "{{ package_uninstall_command }} {{ pulseaudio.packages|join(' ') }}"
  become: False
  register: uninstall
  changed_when: uninstall.rc == 0
  failed_when: "'error: failed to prepare transaction' in uninstall.stderr and uninstall.rc != 0"
  tags: ['packages']
