---

use_bluetooth: True

# network:
#   interfaces:
#     enp2s0:
#       type: ethernet
#       ifname: enp2s0
#       conn_name: enp2s0
#       mac: 58:8a:5a:38:fb:22
#       autoconnect: False
#       state: present
#       method4: disabled
#     wlan0:
#       type: wifi
#       ifname: wlan0
#       conn_name: invisiblemagic
#       mac: C0:25:E9:74:CD:96
#       ssid: invisiblemagic
#       wifi_sec:
#         key_mgmt: wpa-psk
#         psk: b269a69b3a6d38effeb314eb9c95d58782a09c67e54e07865ed45d69a3d96242
#       ip4: 192.168.41.4
#       gw4: 192.168.41.1
#       dns4: 192.168.41.1
#       dns4_search: syncopated.net
#       autoconnect: True
#       state: present
#       method4: manual
#     wlan1:
#       type: wifi
#       ifname: wlan1
#       conn_name: wlan1
#       mac: 9c:30:5b:d8:0c:1f
#       ssid: invisiblemagic
#       autoconnect: False
#       state: present
#       method4: disabled
