---

use_bluetooth: True

# network:
#   interfaces:
#     enp2s0:
#       type: ethernet
#       ifname: enp2s0
#       conn_name: enp2s0
#       mac: 68:1d:ef:2a:b4:03
#       ip4: 192.168.41.26
#       gw4: 192.168.41.1
#       dns4: 192.168.41.1
#       dns4_search: syncopated.net
#       autoconnect: True
#       state: present
#       method4: manual
#     enp3s0:
#       type: ethernet
#       ifname: enp3s0
#       conn_name: audio
#       mac: 68:1d:ef:2a:ac:47
#       ip4: 192.168.36.1
#       autoconnect: True
#       state: present
#       method4: manual
#     wlan0:
#       type: wifi
#       ifname: wlan0
#       conn_name: wlan0
#       mac: c2:03:79:0d:7d:b3
#       autoconnect: False
#       state: present
#       method4: disabled
