---

- name: Ensure redis data directory exists
  file:
    path: "{{ item }}"
    state: directory
    group: devops
    mode: g+s
  with_items:
    - "{{ data }}/redis/local-data"
  become: True

- name: "pull redis/redis-stack:latest"
  docker_image:
    name: redis/redis-stack
    tag: latest
    source: pull
  tags: ['image']

# - name: Verify that chromadb services are not running
#   ansible.builtin.assert:
#     that:
#       - "not output.services.chromadb.chromadb_chromadb_1.state.running"

- name: Start Redis Stack server
  docker_container:
    name: redis-stack
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    # env:
      # REDIS_ARGS: "--requirepass mypassword"
    volumes:
      - "{{ data }}/redis/local-data:/data"
    detach: yes
  tags: ['container']
