---

pkgs__browser:
  - elinks
  - google-chrome
  - lynx
  - qutebrowser
pkgs__desktop:
  # - obs-rtspserver
  # - pgmodeler
  - ascii-image-converter
  - asciiquarium-transparent-git
  - cbonsai
  - dconf
  - dunst
  - fuse3
  - fuse-common
  - gconf
  - hexchat
  - libaudec
  - libcaca
  - libcyaml
  - lsp-dsp-lib
  - lsparu
  - maim
  - network-manager-applet
  - octopi
  - paruz
  - patat-bin
  - pgvector
  - rofi
  - sampler
  - sd
  - sshpass
  - stunnel
  - sudo
  - sysstat
  - taglib
  - thunar
  - thunar-archive-plugin
  - thunar-volman
  - ttf-tw
  - ueberzug
  - unrar
  - unzip
  - wmctrl
  - wmfocus
  - wordnet-cli
  - wordnet-common
  - wordnet-tk
  - xarchiver
  - xclip
  - xdot
  - zenity
pkgs__development:
  - bash-language-server
  - beautysh
  - code-marketplace
  - devdocs-desktop
  - git
  - gitflow-avh
  - gitflow-zshcompletion-avh
  - github-cli
  - gtksourceview3
  - gtksourceview4
  - gtkspell3
  - gummi
  - jc
  - keepassxc
  - meld
  - micro
  - nano-syntax-highlighting
  - neovim
  - neovim-symlinks
  - nodejs
  - npm
  - nyan-lang-git
  - obsidian
pkgs__docs:
  - gnuplot
  - highlight
  - html2md
  - odt2txt
  - open-chinese-fonts
  - pdf2htmlex-appimage
  - pdfjs
  - perl-image-exiftool
  - pod2man
  - poppler
  - qpdf
  - termpdf.py-git
  - texlive-bin
  - texlive-coffee-stains
pkgs__media:
  - cpod-appimage
  - darktable
  - epson-inkjet-printer-escpr2
  - feh
  - ffmpeg4.4
  - ffmpegthumbnailer
  - gimp
  - gpick
  - graphicsmagick
  - imagemagick
  - imv
  - mediainfo
  - mpv
  - mpv-plugin-excerpt-git
  - nitrogen-git
  - obs-studio
  - radiotray-ng
  - shotcut
  - sxiv
  - teiler-git
  - vidcutter
  - vlc
  - yt-dlp
pkgs__python:
  - python-adblock
  - python-chardet
  - python-conda-package-handling
  - python-pagelabels
  - python-pillow
  - python-pympler
  - python-setuptools
  - python-sphinx-intl
  - python-sphinxcontrib-svg2pdfconverter
pkgs__utils:
  - aspell-en
  - barrier
  - firewalld
  - fsarchiver
  - geoclue
  - gnome-common
  - gnome-keyring
  - grsync
  - inxi
  - redshift
  - seahorse
  - timeshift
