---
# vars file for desktop

desktop:
  packages:
    # - libvdpau-va-gl-i965
    # - midieditor
    - ascii-image-converter
    - asciiquarium-transparent-git
    - beautysh
    - cbonsai
    - code-marketplace
    - cpod-appimage
    - devdocs-desktop
    - elinks
    - ffmpegthumbnailer
    - gitflow-zshcompletion-avh
    - google-chrome
    - haskell-connection
    - haskell-x509-store
    - haskell-x509-system
    - haskell-x509-validation
    - highlight
    - html2md
    - imagemagick
    - lazydocker-bin
    - libaudec
    - libcaca
    - libcyaml
    - lsp-dsp-lib
    - lsparu
    - lynx
    - mediainfo
    - neovim-symlinks
    - numix-circle-icon-theme-git
    - numix-icon-theme-git
    - nyan-lang-git
    - obs-rtspserver
    - odt2txt
    - open-chinese-fonts
    - paruz
    - pdf2htmlex-appimage
    - perl-image-exiftool
    - pgmodeler
    - pgvector
    - pod2man
    - poppler
    - python2-setuptools
    - python-chardet
    - python-conda-package-handling
    - python-pagelabels
    - python-pillow
    - python-pympler
    - python-sphinx-intl
    - python-sphinxcontrib-svg2pdfconverter
    - python-ueberzug-git
    - sampler
    - sudo
    - teiler-git
    - termpdf.py-git
    - texlive-coffee-stains
    - transmission-cli
    - ttf-tw
    - ueberzug
    - wordnet-cli
    - wordnet-common
    - wordnet-tk
    - xininfo-git
    - xkill-shortcut
    - xorg-font-utils
    - yt-dpl


vscode:
  extensions:
      - "BeardedBear.beardedicons"
      - "BeardedBear.beardedtheme"
      - "Gruntfuggly.todo-tree"
      - "HuggingFace.huggingface-vscode"
      - "James-Yu.latex-workshop"
      - "bradlc.vscode-tailwindcss"
      - "castwide.solargraph"
      - "darkriszty.markdown-table-prettify"
      - "heybourn.headwind"
      - "ms-azuretools.vscode-docker"
      - "ms-python.python"
      - "redhat.vscode-yaml"
      - "tomoki1207.pdf"
      - "wingrunr21.vscode-ruby"
      - "yzane.markdown-pdf"
      - "zjffun.snippetsmanager"

pulsar:
  packages:
      - atom-beautify
      - atom-jinja2
      - atom-material-syntax
      - blocky
      - color-picker
      - file-type-icons
      - file-types
      - fix-indent-on-paste
      - highlight-colors
      - indent-sort
      - language-ansible
      - language-diff
      - language-docker
      - language-dotfiles
      - language-generic-config
      - language-ini
      - language-markdown
      - markdown-pdf
      - markdown-writer
      - open-terminal-here
      - permanent-delete
      - project-icons
      - project-manager
      - project-plus
      - project-runner
      - project-sidebar
      - ruby-solargraph
      - sb-atom-sonic-pi
      - spacegray-atom-dark-syntax
      - tool-bar
      - vibrant-ink-ruby
