---
# vars file for desktop

expected_value: "role_desktop_varsMain.yml"

vscode:
  extensions:
    - "BeardedBear.beardedicons"
    - "BeardedBear.beardedtheme"
    - "bradlc.vscode-tailwindcss"
    - "castwide.solargraph"
    - "darkriszty.markdown-table-prettify"
    - "Gruntfuggly.todo-tree"
    - "heybourn.headwind"
    - "HuggingFace.huggingface-vscode"
    - "James-Yu.latex-workshop"
    - "leodevbro.blockman"
    - "mblode.pretty-formatter"
    - "Miladfathy.html-color-theme"
    - "ms-azuretools.vscode-docker"
    - "ms-python.python"
    - "ms-python.vscode-pylance"
    - "mutable-ai.mutable-ai"
    - "redhat.vscode-yaml"
    - "samuelcolvin.jinjahtml"
    - "Shopify.ruby-lsp"
    - "tomoki1207.pdf"
    - "yzane.markdown-pdf"
    - "zjffun.snippetsmanager"

pulsar:
  packages:
      - atom-beautify
      - atom-jinja2
      - atom-material-syntax
      - blocky
      - color-picker
      - file-type-icons
      - file-types
      - fix-indent-on-paste
      - highlight-colors
      - indent-sort
      - language-ansible
      - language-diff
      - language-docker
      - language-dotfiles
      - language-generic-config
      - language-ini
      - language-markdown
      - markdown-pdf
      - markdown-writer
      - open-terminal-here
      - permanent-delete
      - project-icons
      - ruby-solargraph
      - sb-atom-sonic-pi
      - spacegray-atom-dark-syntax
      - tool-bar
      - vibrant-ink-ruby
