---

- name: install osc2midi
  package:
    name: osc2midi
    state: present

- name: copy osc2midi config
  copy:
    src: usr/share/osc2midi/touchosc/Beatmachine.omm
    dest: /usr/share/osc2midi/touchosc/Beatmachine.omm
    mode: '0644'
    backup: yes
