---
# tasks file for wayland

- name: Starting wayland tasks
  debug:
    msg: "Starting wayland tasks"

- name: Install wayland packages
  shell: "{{ package_install_command }} {{ packages.wayland|join(' ') }}"
  become: False
  tags: ['packages']
