---

- name: Install sxhkd keybindings
  template:
    src: "etc/skel/.config/sxhkd/sxhkdrc.j2"
    dest: "{{ user.home }}/.config/sxhkd/sxhkdrc"
    owner: root
    group: root
    mode: "0644"
    backup: yes
  register: keybindings
  tags: ["profile", "sxhkd", "keybindings", "i3"]
