---
# vars file for i3

__i3_workspaces:
  - workspace:
    id: 1
    name: " 1 "
  - workspace:
    id: 2
    name: " 2 "
  - workspace:
    id: 3
    name: " 3 "
  - workspace:
    id: 4
    name: " 4 "
  - workspace:
    id: 5
    name: " 5 "
  - workspace:
    id: 6
    name: " 6 "
  - workspace:
    id: 7
    name: " 7 "
  - workspace:
    id: 8
    name: " 8 "
  - workspace:
    id: 9
    name: " 9 "
  - workspace:
    id: 0
    name: " 0 "
