---

- name: Current packages installed
  shell: |
    paru -Q |awk '{print $1}'
  become: False
  register: arch_installed_packages
  check_mode: no
  tags: ['packages']

- name: arch_installed_packages
  set_fact:
    installed_packages: "{{ arch_installed_packages.stdout }}"

- block:
    - name: Install Base packages
      aur:
        use: paru
        name: "{{ item }}"
        state: present
        extra_args: "--overwrite '*'"
      with_items:
        - "{{ base_packages|difference(installed_packages) }}"

    - name: Install Desktop packages
      aur:
        use: paru
        name: "{{ item }}"
        state: present
        extra_args: "--overwrite '*'"
      with_items:
        - "{{ desktop_packages|difference(installed_packages) }}"

    - name: Install Docker packages
      aur:
        use: paru
        name: "{{ item }}"
        state: present
        extra_args: "--overwrite '*'"
      with_items:
        - "{{ desktop_packages|difference(installed_packages) }}"

    - name: Install Theme packages
      aur:
        use: paru
        name: "{{ item }}"
        state: present
        extra_args: "--overwrite '*'"
      with_items:
        - "{{ theme_packages|difference(installed_packages) }}"

    - name: Install Tuning packages
      aur:
        use: paru
        name: "{{ item }}"
        state: present
        extra_args: "--overwrite '*'"
      with_items:
        - "{{ tuning_packages|difference(installed_packages) }}"

    - name: Install X11 packages
      aur:
        use: paru
        name: "{{ item }}"
        state: present
        extra_args: "--overwrite '*'"
      with_items:
        - "{{ x11_packages|difference(installed_packages) }}"

    - name: Install DAW packages
      aur:
        use: paru
        name: "{{ item }}"
        state: present
        extra_args: "--overwrite '*'"
      with_items:
        - "{{ daw_packages.archlinux|difference(installed_packages) }}"

  rescue:
    - name: Handle installation failure
      debug:
        msg: "Failed to install a package. Check the logs."

  always:
    - name: Continue executions
      debug:
        msg: "Continuing with playbook execution."

  become: False

- block:
    - name: Install host specific xorg packages
      aur:
        use: paru
        name: "{{ host.xorg.video|difference(arch_installed_packages.stdout) }}"
        state: present
        extra_args: "--overwrite '*'"
      when: host.xorg.video is defined

  rescue:
    - name: Handle installation failure
      debug:
        msg: "Failed to install a package. Check the logs."

  always:
    - name: Continue executions
      debug:
        msg: "Continuing with playbook execution."

  become: False
  tags: ["x11"]
