---

- name: Current packages installed
  shell: |
    paru -Q |awk '{print $1}'
  become: False
  register: arch_installed_packages
  check_mode: no
  tags: ['packages']

- block:
    - name: install packages
      aur:
        use: paru
        name: "{{ packages|difference(arch_installed_packages.stdout) }}"
        state: present
        extra_args: "--overwrite '*'"
      become: False
      when: arch_installed_packages | length > 0
      tags: ['packages']

  rescue:
    - name: Handle installation failure
      debug:
        msg: "Failed to install a package. Check the logs."

  always:
    - name: Continue executions
      debug:
        msg: "Continuing with playbook execution."

  become: False
  tags: ['packages']


- block:
    - name: Install host specific xorg packages
      aur:
        use: paru
        name: "{{ host.xorg.video|difference(arch_installed_packages.stdout) }}"
        state: present
        extra_args: "--overwrite '*'"
      when: host.xorg.video is defined

  rescue:
    - name: Handle installation failure
      debug:
        msg: "Failed to install a package. Check the logs."

  always:
    - name: Continue executions
      debug:
        msg: "Continuing with playbook execution."      

  become: False
  tags: ["x"]
