app:
  description: "Your task is to generate a research objective based on this query.\
    \ To do this:\n1. Carefully read the query and identify the key elements, themes,\
    \ issues or questions that could potentially be addressed through research. \n\
    2. Brainstorm 2-3 potential research objectives that build upon these key elements.\
    \ Write out your brainstorming process and the potential objectives inside <scratchpad>\
    \ tags.\n3. Select the research objective from your brainstorming that you think\
    \ is the most promising, clear, specific and actionable. The objective should\
    \ directly address the core issue or question raised in the query.\n"
  icon: "\U0001F916"
  icon_background: '#FFEAD5'
  mode: workflow
  name: Convert Query to Objective
workflow:
  features:
    file_upload:
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - remote_url
        - local_file
    opening_statement: ''
    retriever_resource:
      enabled: false
    sensitive_word_avoidance:
      configs: []
      enabled: false
      type: ''
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        sourceType: start
        targetType: llm
      id: start-llm
      source: start
      sourceHandle: source
      target: llm
      targetHandle: target
      type: custom
    - data:
        isInIteration: false
        sourceType: llm
        targetType: end
      id: 1718804576889-source-end-target
      source: '1718804576889'
      sourceHandle: source
      target: end
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: llm
        targetType: llm
      id: llm-source-1718864873833-target
      source: llm
      sourceHandle: source
      target: '1718864873833'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: llm
        targetType: tool
      id: 1718864873833-source-1718864516062-target
      source: '1718864873833'
      sourceHandle: source
      target: '1718864516062'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: tool
        targetType: llm
      id: 1718864516062-source-1718804576889-target
      source: '1718864516062'
      sourceHandle: source
      target: '1718804576889'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        selected: false
        title: START
        type: start
        variables:
        - default: ''
          description: null
          hint: null
          label: Query
          max_length: null
          options: null
          required: true
          type: paragraph
          variable: query
        - label: format
          max_length: 48
          options:
          - JSON
          - XML
          - Text
          - Markdown Table
          required: true
          type: select
          variable: format
      height: 115
      id: start
      position:
        x: 30
        y: 272.5
      positionAbsolute:
        x: 30
        y: 272.5
      selected: false
      type: custom
      width: 244
    - data:
        context:
          enabled: false
          variable_selector: null
        memory: null
        model:
          completion_params:
            response_format: JSON
            stop: []
          mode: chat
          name: gemini-1.5-pro-latest
          provider: google
        prompt_template:
        - id: c196b056-e7e2-4764-83a1-4da4d1e7d913
          role: user
          text: "Here is a query that was submitted:\n<query>\n{{#start.query#}}\n\
            </query>\nYour task is to generate a research objective based on this\
            \ query. To do this:\n1. Carefully read the query and identify the key\
            \ elements, themes, issues or questions that could potentially be addressed\
            \ through research. \n2. Brainstorm 2-3 potential research objectives\
            \ that build upon these key elements. Write out your brainstorming process\
            \ and the potential objectives inside <scratchpad> tags.\n3. Select the\
            \ research objective from your brainstorming that you think is the most\
            \ promising, clear, specific and actionable. The objective should directly\
            \ address the core issue or question raised in the query.\n\nRemember,\
            \ a good research objective is clear, specific enough to be addressed\
            \ through research, and directly relevant to the original query. Let your\
            \ brainstorming process guide you, but make sure to refine the objective\
            \ you ultimately select.\n\nDo not include any intermediate working or\
            \ scratchpad. Only output the determined objective."
        selected: true
        title: determine objective
        type: llm
        vision:
          configs: null
          enabled: false
          variable_selector: null
      height: 97
      id: llm
      position:
        x: 333
        y: 272.5
      positionAbsolute:
        x: 333
        y: 272.5
      selected: true
      type: custom
      width: 244
    - data:
        outputs:
        - value_selector:
          - llm
          - text
          variable: objective
        - value_selector:
          - '1718804576889'
          - text
          variable: tasks
        selected: false
        title: END
        type: end
      height: 115
      id: end
      position:
        x: 1545
        y: 272.5
      positionAbsolute:
        x: 1545
        y: 272.5
      selected: false
      type: custom
      width: 244
    - data:
        context:
          enabled: true
          variable_selector:
          - '1718864516062'
          - text
        desc: ''
        model:
          completion_params:
            temperature: 0.4
          mode: chat
          name: gemini-1.5-pro-latest
          provider: google
        prompt_template:
        - id: 56e0599c-05c1-4782-b017-f0c509cda4b0
          role: system
          text: "Please generate list of tasks to complete an objective. \n<objective>\n\
            {{#llm.text#}}\n</objective>\n\nUse search results related to the objective\
            \ as additional context.\n\n<additional_context>\n{{#context#}}\n</additional_context>\n\
            \nOutput the task list in {{#start.format#}}format"
        selected: false
        title: generate tasks
        type: llm
        variables: []
        vision:
          configs:
            detail: high
          enabled: true
      height: 97
      id: '1718804576889'
      position:
        x: 1242
        y: 272.5
      positionAbsolute:
        x: 1242
        y: 272.5
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        provider_id: searchapi
        provider_name: searchapi
        provider_type: builtin
        selected: false
        title: Google Search API
        tool_configurations:
          gl: US
          hl: en
          result_type: text
        tool_label: Google Search API
        tool_name: google_search_api
        tool_parameters:
          location:
            type: mixed
            value: Columbus
          query:
            type: mixed
            value: '{{#1718864873833.text#}}'
        type: tool
      height: 141
      id: '1718864516062'
      position:
        x: 939
        y: 272.5
      positionAbsolute:
        x: 939
        y: 272.5
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        context:
          enabled: true
          variable_selector:
          - llm
          - text
        desc: Generate Search Query Based On Objective
        model:
          completion_params:
            temperature: 0.7
          mode: chat
          name: gemini-1.5-pro-latest
          provider: google
        prompt_template:
        - id: ce2aec31-f2dc-43ae-8a8e-0203df8c63a7
          role: system
          text: 'Generate a relevant search query based on context provided:

            <context>

            {{#context#}}

            </context>

            Output only the generated search query. '
        selected: false
        title: generate query
        type: llm
        variables: []
        vision:
          configs:
            detail: high
          enabled: true
      height: 145
      id: '1718864873833'
      position:
        x: 636
        y: 272.5
      positionAbsolute:
        x: 636
        y: 272.5
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: 364.0000000000002
      y: 156.99999999999994
      zoom: 0.7
