app:
  description: ''
  icon: "\U0001F916"
  icon_background: '#FFEAD5'
  mode: advanced-chat
  name: README Bot
workflow:
  features:
    file_upload:
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
    opening_statement: ''
    retriever_resource:
      enabled: false
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        sourceType: start
        targetType: llm
      id: 1719770352415-llm
      source: '1719770352415'
      sourceHandle: source
      target: llm
      targetHandle: target
      type: custom
    - data:
        sourceType: llm
        targetType: answer
      id: llm-answer
      source: llm
      sourceHandle: source
      target: answer
      targetHandle: target
      type: custom
    nodes:
    - data:
        desc: ''
        selected: false
        title: Start
        type: start
        variables:
        - label: codeFunctions
          max_length: null
          options: []
          required: true
          type: paragraph
          variable: codeFunctions
        - label: projectName
          max_length: null
          options: []
          required: true
          type: text-input
          variable: projectName
      height: 129
      id: '1719770352415'
      position:
        x: 80
        y: 282
      positionAbsolute:
        x: 80
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    - data:
        context:
          enabled: false
          variable_selector: []
        desc: ''
        memory:
          role_prefix:
            assistant: ''
            user: ''
          window:
            enabled: false
            size: 10
        model:
          completion_params:
            temperature: 0.7
          mode: chat
          name: gemini-1.5-pro-latest
          provider: google
        prompt_template:
        - id: bf0b8f33-2e5a-4f3b-8736-851734259de8
          role: system
          text: "Generate a README.md file for a project named \"{{#1719770352415.projectName#}}\"\
            \ with the following code functions: \n{{#1719770352415.codeFunctions#}}\n\
            The README should include:\n1. A brief introduction explaining the project's\
            \ purpose.\n2. A list of the project's main features.\n3. Installation\
            \ and setup instructions.\n4. Basic usage instructions or examples.\n\
            5. Dependencies or requirements (if applicable).\n6. Brief contribution\
            \ guidelines.\n7. License information.\nWrite the README with a dry, sarcastic,\
            \ and conversational tone. Imagine you're a slightly exasperated developer\
            \ explaining the project. \nPresent your README.md content within `<readme>`\
            \ tags using proper Markdown syntax."
        selected: true
        title: LLM
        type: llm
        variables: []
        vision:
          configs:
            detail: high
          enabled: true
      height: 109
      id: llm
      position:
        x: 380
        y: 282
      positionAbsolute:
        x: 380
        y: 282
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    - data:
        answer: '{{#llm.text#}}'
        desc: ''
        selected: false
        title: Answer
        type: answer
        variables: []
      height: 116
      id: answer
      position:
        x: 680
        y: 282
      positionAbsolute:
        x: 680
        y: 282
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    viewport:
      x: 0
      y: 0
      zoom: 1
