app:
  description: You will be identifying and extracting key topics from sections of
    a provided text. The text will be broken up into segments, and for each segment
    you will determine the main topics discussed along with a confidence score.
  icon: "\U0001F916"
  icon_background: '#FFEAD5'
  mode: workflow
  name: Topics and Intents - Workflow
workflow:
  features:
    file_upload:
      image:
        enabled: true
        number_limits: 3
        transfer_methods:
        - remote_url
        - local_file
    opening_statement: ''
    retriever_resource:
      enabled: false
    sensitive_word_avoidance:
      configs: []
      enabled: false
      type: ''
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        sourceType: llm
        targetType: end
      id: llm-end
      selected: false
      source: llm
      sourceHandle: source
      target: end
      targetHandle: target
      type: custom
    - data:
        isInIteration: false
        sourceType: start
        targetType: llm
      id: start-source-llm-target
      source: start
      sourceHandle: source
      target: llm
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        selected: false
        title: START
        type: start
        variables:
        - default: ''
          description: null
          hint: null
          label: transcript
          max_length: null
          options: null
          required: true
          type: paragraph
          variable: transcript
        - default: ''
          description: null
          hint: null
          label: context
          max_length: null
          options: null
          required: true
          type: paragraph
          variable: context
      height: 115
      id: start
      position:
        x: 30
        y: 257.5
      positionAbsolute:
        x: 30
        y: 257.5
      selected: false
      type: custom
      width: 244
    - data:
        context:
          enabled: false
          variable_selector: null
        memory: null
        model:
          completion_params:
            frequency_penalty: 0.6
            k: 100
            max_tokens: 4096
            stop: []
            temperature: 0.3
          mode: chat
          name: claude-3-opus-20240229
          provider: anthropic
        prompt_template:
        - id: 7bcb3cff-e2a6-48e3-8f05-99eaaf123e5f
          role: user
          text: "You will be identifying and extracting key topics from sections of\
            \ a provided text. The text will be broken up into segments, and for each\
            \ segment you will determine the main topics discussed along with a confidence\
            \ score.\nHere is the text to analyze:\n<text>\n{{#start.transcript#}}\n\
            </text>\n\nFirst, break the text up into segments of 1-3 sentences each.\
            \ For each segment, determine the start and end word numbers.\n\nThen,\
            \ for each text segment, identify the key topics discussed in that segment.\
            \ Aim to extract 1-3 topics per segment, focusing on the most important\
            \ and relevant topics. Within the text segment, identify any text expressing\
            \ intents like thinking out-loud, asking a question, observing, analyzing\
            \ a topic, describing a process, etc. For each topic, also provide a confidence\
            \ score between 0 and 1 indicating how confident you are that the topic\
            \ is a main focus of that segment. \n\nConsider the additional context\
            \ when identifying topics and intents:\n\n<additional_context>\n{{#start.context#}}\n\
            </additional_context>\n\nFinally, format the results into the following\
            \ JSONL structure:\n```jsonl\n{\"text\": \"<text of first segment>\",\
            \ \"start_word\": <number of first word in segment>, \"end_word\": <number\
            \ of last word in segment>, \"topics\": [{\"topic\": \"<first topic>\"\
            , \"confidence_score\": <confidence score for first topic>}, {\"topic\"\
            : \"<second topic, if applicable>\", \"confidence_score\": <confidence\
            \ score for second topic>}], \"intents\": [{\"intent\": \"(intent label)\"\
            , \"confidence_score\": (decimal score)}]}\n{\"text\": \"<text of second\
            \ segment>\", \"start_word\": <number of first word in segment>, \"end_word\"\
            : <number of last word in segment>, \"topics\": [{\"topic\": \"<first\
            \ topic>\", \"confidence_score\": <confidence score for first topic>}],\
            \ \"intents\": [{\"intent\": \"(intent label)\", \"confidence_score\"\
            : (decimal score)}]}\n...\n\nDo not include any intermediate working or\
            \ scratchpad. Only output the final complete JSONL.\n"
        selected: true
        title: LLM
        type: llm
        vision:
          configs:
            detail: high
          enabled: true
      height: 97
      id: llm
      position:
        x: 333
        y: 257.5
      positionAbsolute:
        x: 333
        y: 257.5
      selected: true
      type: custom
      width: 244
    - data:
        outputs:
        - value_selector:
          - llm
          - text
          variable: result
        selected: false
        title: END
        type: end
      height: 89
      id: end
      position:
        x: 636
        y: 257.5
      positionAbsolute:
        x: 636
        y: 257.5
      selected: false
      type: custom
      width: 244
    viewport:
      x: 441.75000000000006
      y: 340.1
      zoom: 0.7
