---
# tasks file for xorg
- name: Xorg Tasks
  debug:
    msg: "Starting xorg tasks"

- name: Set xorg.conf
  template:
    src: etc/X11/xorg.conf.j2
    dest: /etc/X11/xorg.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  tags: ["video"]

- name: Disable vblank
  copy:
    src: home/.drirc
    dest: "{{ user.home }}/.drirc"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  tags: ["video"]

- name: Install xorg configs
  template:
    src: "home/{{ item }}.j2"
    dest: "{{ user.home }}/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0644"
    backup: yes
  with_items:
    - .xprofile
    - .xserverrc
    - .Xresources
  register: xconfig
  changed_when: (xconfig.msg is defined and not 'All items completed' in xconfig.msg)
  tags: ['env', 'profile']

- name: Install xinitc
  template:
    src: home/.xinitrc.j2
    dest: "{{ user.home }}/.xinitrc"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0755'
    backup: True

# - name: Ensure .xinitrc is executable
#   file:
#     path: "{{ user.home }}/.xinitrc"
#     mode: "0755"
#   ignore_errors: "{{ ansible_check_mode }}"
#   tags: ['env', 'profile']

- block:
    - name: Set video modules in mkinitcpio
      template:
        src: etc/mkinitcpio.conf.j2
        dest: /etc/mkinitcpio.conf
        owner: root
        group: root
        mode: '0644'
        backup: yes
      register: mkinitcpio_conf

    - name: Re-create ramdisk if config changed
      shell: mkinitcpio -P
      when: mkinitcpio_conf.changed

  # when: ansible_facts["lsb"]["id"] != 'EndeavourOS'
  when: ansible_distribution != 'EndeavourOS'
  tags: ['mkinitcpio']

# - import_tasks:
#     file: sxhkd.yml
#   tags: ['sxhkd', 'keybindings']

- import_tasks:
    file: xdg.yml
  tags: ['xdg', 'profile']
