---
# tasks file for xorg
- name: Xorg Tasks
  debug:
    msg: "Starting xorg tasks"

- block:
    - name: Install system xorg packages
      aur:
        use: paru
        name: "{{ packages.xorg }}"
        state: present

    - name: Install host specific xorg packages
      aur:
        use: paru
        name: "{{ host.xorg.video }}"
        state: present
      when: host.xorg.video is defined

  become: False
  tags: ["packages"]

- name: Set xorg.conf
  template:
    src: etc/X11/xorg.conf.j2
    dest: /etc/X11/xorg.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  tags: ["video"]

- name: Disable vblank
  copy:
    src: etc/skel/.drirc
    dest: "{{ user.home }}/.drirc"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  tags: ["video"]

- name: Install xorg configs
  template:
    src: "etc/skel/{{ item }}.j2"
    dest: "{{ user.home }}/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0644"
    backup: yes
  with_items:
    - .xinitrc
    - .xprofile
    - .xserverrc
    - .Xresources
  register: xconfig
  tags: ['env', 'profile']

- name: Ensure .xinitrc is executable
  file:
    path: "{{ user.home }}/.xinitrc"
    mode: "0755"
  ignore_errors: "{{ ansible_check_mode }}"
  tags: ['env', 'profile']

- name: Ensure user belongs to audio group
  user:
    name: "{{ item.name }}"
    groups: "video"
    append: yes
  with_items: "{{ users }}"

- import_tasks:
    file: sxhkd.yml
  tags: ['sxhkd', 'keybindings']

- import_tasks:
    file: xdg.yml
  tags: ['xdg', 'profile']
