---
# tasks file for flowise


- block:
    - name: Clone repository
      git:
        repo: "{{ flowise.repo }}"
        dest: "{{ flowise.path }}"
        recursive: yes
        accept_hostkey: yes
        update: no
        force: no
        version: "{{ flowise.version }}"
      check_mode: no

    - name: show env vars
      debug:
        msg: "{{ env.vars }}"

    - name: Install docker file templates
      template:
        src: "{{ item }}.j2"
        dest: "{{ flowise.path }}/docker/{{ item }}"
        mode: '0644'
        backup: True
      loop:
        - docker-compose.yml
        - .env

  become: False
