---
pkgs__audio_codecs:
  - faac
  - faad2
  - fftw
  - flac
  - gst-libav
  - gst-plugins-bad
  - gst-plugins-bad-libs
  - gst-plugins-base
  - gst-plugins-base-libs
  - gst-plugins-good
  - gstreamer
  - lame
  - opus
  - opus-tools
  - opusfile
  - vorbis-tools
  - wavpack
  - x264
  - x265
