---

vscode:
  extensions:
    - "10nates.ollama-autocoder"
    - "beardedbear.beardedicons"
    - "beardedbear.beardedtheme"
    - "bradlc.vscode-tailwindcss"
    - "byi8220.indented-block-highlighting"
    - "castwide.solargraph"
    - "darkriszty.markdown-table-prettify"
    - "esbenp.prettier-vscode"
    - "foxundermoon.shell-format"
    - "github.vscode-github-actions"
    - "gruntfuggly.todo-tree"
    - "heybourn.headwind"
    - "huggingFace.huggingface-vscode"
    - "james-Yu.latex-workshop"
    - "jokela.vscode-sfz"
    - "kentor.sort-indentation-group"
    - "kevinrose.vsc-python-indent"
    - "leodevbro.blockman"
    - "mblode.pretty-formatter"
    - "miladfathy.html-color-theme"
    - "ms-azuretools.vscode-docker"
    - "ms-azuretools.vscode-docker"
    - "ms-python.debugpy"
    - "ms-python.python"
    - "ms-python.vscode-pylance"
    - "ms-toolsai.jupyter"
    - "ms-toolsai.jupyter-keymap"
    - "ms-toolsai.jupyter-renderers"
    - "ms-toolsai.vscode-jupyter-cell-tags"
    - "ms-toolsai.vscode-jupyter-slideshow"
    - "ms-vscode-remote.remote-ssh"
    - "ms-vscode-remote.remote-ssh-edit"
    - "ms-vscode.remote-explorer"
    - "njpwerner.autodocstring"
    - "redhat.vscode-yaml"
    - "renxzen.google-monokai-theme"
    - "samuelcolvin.jinjahtml"
    - "shopify.ruby-lsp"
    - "textworld.textworld-vscode"
    - "the-e3n.block-highlighter"
    - "tomoki1207.pdf"
    - "yzane.markdown-pdf"
    - "zjffun.snippetsmanager"

pulsar:
  packages:
      - atom-beautify
      - atom-jinja2
      - atom-material-syntax
      - blocky
      - color-picker
      - file-type-icons
      - file-types
      - fix-indent-on-paste
      - highlight-colors
      - indent-sort
      - language-ansible
      - language-diff
      - language-docker
      - language-dotfiles
      - language-generic-config
      - language-ini
      - language-markdown
      - markdown-pdf
      - markdown-writer
      - open-terminal-here
      - permanent-delete
      - project-icons
      - ruby-solargraph
      - sb-atom-sonic-pi
      - spacegray-atom-dark-syntax
      - tool-bar
      - vibrant-ink-ruby
