---
# defaults file for common

# The default directory permission mode when creating directories using `root_directory_definitions`
root_directory_default_mode: '0755'

# The default directory owner when creating directories using `root_directory_definitions`
root_directory_default_owner: root

# The default directory group when creating directories using `root_directory_definitions`
root_directory_default_group: root

root_directory_default_recurse: False

root_directory_definitions:
  - dest: /etc/X11/xorg.conf.d
  - dest: /etc/fonts
  - dest: /etc/pulse/default.pa.d
  - dest: /etc/systemd/timesyncd.conf.d
  - dest: /etc/xdg
  - dest: /etc/mediamtx
  - dest: /etc/autofs
  - dest: /usr/share/backgrounds

expected_value: "role_base_defaults"

base__packages:
  # - asciiquarium-transparent-git
  # - crossguid
  # - html2md
  # - lnav-git
  # - nyan-lang-git
  # - python-conda-package-handling
  - ascii-image-converter
  - asciiquarium-git
  - aspell
  - aspell-en
  - atool
  - audiofile
  - autofs
  - await
  - bandwhich
  - bash-completion
  - bash-language-server
  - bat
  - beautysh
  - bottom
  - choose
  - chromaprint
  - cmake
  - cpupower
  - curlie
  - dex
  - doggo
  - downgrade
  - duf
  - dust
  - elinks
  - eza
  - faac
  - faad2
  - fd
  - figlet
  - firewalld
  - fsarchiver
  - fuse3
  - fuse-common
  - git
  - git-delta
  - git-lfs
  - github-cli
  - gitui
  - glow
  - gnome-keyring
  - gnuplot
  - gource
  - gping
  - graphicsmagick
  - gst-libav
  - gstreamer
  - gum
  - highlight
  - hspell
  - htop
  - i7z
  - imagemagick
  - inetutils
  - inxi
  - iotop
  - jq
  - libcyaml
  - libgit2
  - libgit2-glib
  - libvips
  - libvoikko
  - links
  - lnav
  - lynx
  - mako
  - mediainfo
  - meld
  - micro
  - mlocate
  - most
  - mupdf-tools
  - nano-syntax-highlighting
  - ncdu
  - net-tools
  - nodejs
  - npm
  - numlockx
  - nuspell
  - odt2txt
  - openssl
  - opus
  - opus-tools
  - opusfile
  - pamixer
  - pandoc-cli
  - pdf2htmlex-appimage
  - pdfjs
  - perl-image-exiftool
  - pgvector
  - platformfolders
  - playerctl
  - pod2man
  - poppler
  - postgresql-libs
  - poweralertd
  - python-adblock
  - python-chardet
  - python-j2cli
  - python-pagelabels
  - python-pillow
  - python-pygments
  - python-pympler
  - python-setuptools
  - python-sphinx-intl
  - python-sphinxcontrib-svg2pdfconverter
  - qpdf
  - ranger
  - ripgrep
  - ripgrep-all
  - rsync
  - rxvt-unicode
  - sd
  - smartmontools
  - socat
  - speech-dispatcher
  - sshpass
  - stunnel
  - sudo
  - swappy
  - sysstat
  - taglib
  - teiler-git
  - texlive-basic
  - texlive-bin
  # - texlive-coffee-stains
  - texlive-doc
  - texlive-fontsextra
  - texlive-fontsrecommended
  - texlive-latex
  - texlive-latexextra
  - texlive-latexrecommended
  - texlive-pictures
  - texlive-xetex
  - tldr
  - transmission-cli
  - tree
  - ueberzug
  - unrar
  - unzip
  - v4l-utils
  - vorbis-tools
  - wavpack
  - wget
  - wkhtmltopdf-static
  - wmctrl
  - wordnet-cli
  - wordnet-common
  - x264
  - x265
  - xterm
  - yad
  - yt-dlp
  - zoxide
