---

- name: Applications Tasks
  debug:
    msg: "Starting applications role tasks"

- name: Ensure application directories exist
  file:
    path: "{{ application_directory_default_location }}/{{ item.dest }}"
    state: directory
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    recurse: "{{ item.recurse | default(false) }}"
  loop: "{{ application_directory_definitions }}"
  check_mode: no
  tags: ['profile']

- import_tasks:
    file: dev/pulsar.yml
  when: pulsar is defined
  tags: ['pulsar']

- import_tasks:
    file: dev/vscode.yml
  when: vscode is defined
  tags: ['vscode']


- import_tasks:
    file: media/deadbeef.yml
  when: deadbeef is defined
  tags: ['media', 'deadbeef']

- import_tasks:
    file: media/mixxx.yml
  when: mixxx is defined
  tags: ['mixxx']


- name: Set mediamtx config
  copy:
    src: etc/mediamtx/mediamtx.yml
    dest: /etc/mediamtx/mediamtx.yml
    backup: True
  tags: ['mediamtx']

- name: Enable mediamtx service
  service:
    name: mediamtx
    state: stopped
    enabled: True
  when: serivces.mediamtx.enabled is defined
  tags: ['mediamtx']
