---

- name: install applications packages
  aur:
    use: paru
    name: "{{ applications__packages }}"
    state: present
  become: False
  when: ansible_os_family == "Archlinux"
  tags: ['packages']
