---

- name: install devtools and inotify-tools
  pacman:
    name: "{{ item }}"
    state: present
    force: yes
    extra_args: --noconfirm
  with_items:
    - devtools
    - inotify-tools
  tags: ['packages']

- name: Copy makepkg and pacman templates to workspace
  template:
    src: "etc/{{ item }}.j2"
    dest: "{{ packager.workspace }}/archlinux/pkgbuids/{{ item }}"
    owner: "{{ packager.name }}"
    group: devops
    mode: '0664'
  with_items:
    - makepkg-x86_64.conf
    - makepkg-x86_64_v3.conf
    - pacman-x86_64.conf
    - pacman-x86_64_v3.conf

- name: Install build scripts
  copy:
    src: "usr/local/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: devops
    mode: '0775'
    backup: True
  with_items:
      - build.sh
      - deploy.sh
