---
- name: create devops group
  group:
    name: devops
    state: present
    gid: 1041

- name: add packager to the devops group
  user:
    name: "{{ packager.name }}"
    groups: devops
    append: True

- name: clone the Packages repository
  git:
    repo: git@github.com:b08x/packages.git
    dest: /tmp/syncopated/Packages
    recursive: yes
    accept_hostkey: yes
    update: no
    force: no
  check_mode: no


- name: Create packager workspace folder
  file:
    path: "{{ packager.workspace }}/{{ item }}"
    state: directory
    owner: "{{ packager.name }}"
    group: devops
    mode: "2775"
    recurse: True
  with_items:
    - archlinux/pkgbuids
    - Fedora/specs



- name: Create distro repo folder tree
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ packager.name }}"
    group: devops
    mode: "2775"
    recurse: True
  with_items:
    - "{{ repos.archlinux.packages }}"
    - "{{ repos.archlinux.src_packages }}"
    - "{{ repos.archlinux.x86_64 }}"
    - "{{ repos.archlinux.x86_64_v3 }}"

- name: Create distro repo folder tree
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ packager.name }}"
    group: devops
    mode: "2775"
    recurse: True
  with_items:
    - "{{ repos.Fedora.packages }}"
    - "{{ repos.Fedora.src_packages }}"
    - "{{ repos.Fedora.x86_64 }}"
    - "{{ repos.Fedora.x86_64_v3 }}"


- name: Load distro tasks
  import_tasks:
    file: Archlinux.yml
  when: ansible_distribution == 'Archlinux'
