---
# tasks file for zsh

- name: Starting zsh tasks
  debug:
    msg: "Starting zsh tasks"

- name: Install oh-my-zsh
  shell: |
    if [ ! -d "/usr/local/share/oh-my-zsh" ]; then
      export ZSH="/usr/local/share/oh-my-zsh"
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    fi

- name: Install zsh custom functions
  synchronize:
    src: etc/skel/.zsh/
    dest: /etc/skel/.zsh/
    recursive: yes
    mode: push
    delete: no
    checksum: yes
    perms: no
    rsync_opts:
      - "--update"
      - "--omit-dir-times"
      - "--progress"
      - "--itemize-changes"
      - "--chown=root:root"
      - "--backup"
      - "--suffix={{ suffix }}"
  ignore_errors: "{{ ansible_check_mode }}"
  tags: ['env', 'profile']

- name: Set zsh profile configs
  template:
    src: "etc/skel/{{ item }}.j2"
    dest: "/etc/skel/{{ item }}"
    owner: root
    group: root
    mode: '0644'
    backup: True
  with_items:
    - .zprofile
    - .zshenv
    - .zshrc
  tags: ['env', 'profile']
