---
# tasks file for audio

- name: Include distro vars
  include_vars:
    file: vars/{{ ansible_distribution }}.yml
  tags: ['always']

- name: Install audio codec packages
  shell: "{{ package_install_command }} {{ audio.packages.codecs|join(' ') }}"
  become: False
  tags: ['packages']
