---
# tasks file for audio

- name: Audio Tasks
  debug:
    msg: "Starting audio tasks"

- name: Ensure root directories exist
  file:
    dest: "{{ item.dest }}"
    state: directory
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    recurse: "{{ item.recurse | default(false) }}"
  loop: "{{ audio_directory_definitions }}"

- import_tasks:
    file: tuning.yml
  tags: ["tuning", "realtime"]
