---
# tasks file for audio

- name: Include distro vars
  include_vars:
    file: vars/{{ ansible_distribution }}.yml
  tags: ['always']

- name: Install audio codec packages
  shell: "{{ package_install_command }} {{ item }}"
  with_items:
    - "{{ audio.packages.codecs }}"
  become: False
  tags: ['packages']
