---
# tasks file for audio

- name: Starting audio tasks
  debug:
    msg: "Starting audio tasks"

- name: Include distro vars
  include_vars:
    file: vars/{{ ansible_distribution }}.yml
  tags: ['always']

- name: Install audio codec packages
  shell: "{{ package_install_command }} {{ audio.packages.codecs|join(' ') }}"
  become: False
  tags: ['packages']

- name: Ensure root directories are created
  file:
    dest: "{{ item.dest }}"
    state: directory
    owner: "{{ item.owner | default(audio_directory_default_owner) }}"
    group: "{{ item.group | default(audio_directory_default_group) }}"
    mode: "{{ item.mode | default(audio_directory_default_mode) }}"
    recurse: "{{ item.recurse | default(audio_directory_default_recurse) }}"
  with_items: "{{ audio_directory_definitions }}"
  tags: ['always']

- import_tasks:
    file: tuning.yml
  tags: ['tuning', 'realtime']
