---
# tasks file for i3

- name: Starting i3 tasks
  debug:
    msg: "Starting i3 tasks"

- name: Include distro vars
  include_vars:
    file: vars/{{ ansible_distribution }}.yml

- name: Show desktop variables
  debug:
    msg: "{{ i3 }}"

- name: Install i3 packages
  shell: "{{ package_install_command }} {{ i3__pkgs | join(' ') }}"
  become: False
  tags: ['packages']

- name: Install i3ipc module
  pip:
    name: i3ipc
    executable: pip
    state: present
    extra_args: --break-system-packages
  tags: ['packages', 'python']

- name: Create i3 scripts folder
  file:
    path: /usr/share/i3/scripts
    state: directory
    owner: root
    group: root

- name: Install i3autolayout.py
  copy:
    src: usr/share/i3/scripts/i3autolayout.py
    dest: "/usr/share/i3/scripts/i3autolayout.py"
    mode: '0755'
  tags: ['packages']

- block:
    - name: Set i3 configuration
      template:
        src: "etc/skel/{{ item }}.j2"
        dest: "/etc/skel/{{ item }}"
        owner: root
        group: root
        mode: '0644'
        backup: yes
      register: wmconfig
      with_items:
        - .config/i3/config
        - .config/i3/window_behavior
        - .config/i3/modes/resize
        - .config/i3/keybindings
        - .config/i3/appearance
        - .config/i3/window_assignments
        - .config/i3/autostart

    - name: Set i3status-rs configuration
      template:
        src: "etc/skel/{{ item }}.j2"
        dest: "/etc/skel/{{ item }}"
        owner: root
        group: root
        mode: '0644'
        backup: yes
      register: wmconfig
      with_items:
        - .config/i3status-rust/config.toml
        - .config/i3status-rust/themes/syncopated.toml

  tags: ['profile']
