---
# tasks file for i3

- name: i3 Tasks
  debug:
    msg: "Starting i3 tasks"

- name: Show i3 variables
  debug:
    var: i3

- name: Ensure i3 directories exist
  file:
    dest: "{{ i3_directory_default_location }}/{{ item.dest }}"
    state: directory
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    recurse: "{{ item.recurse | default(false) }}"
  loop: "{{ i3_directory_definitions }}"
  check_mode: no
  tags: ['profile']

- name: Install i3ipc module
  pip:
    name: i3ipc
    executable: pip
    state: present
    extra_args: --break-system-packages
  tags: ['packages', 'python']

- name: Create i3 scripts folder
  file:
    path: /usr/share/i3/scripts
    state: directory
    owner: root
    group: root

- block:
    - name: Set i3 configuration
      template:
        src: "home/{{ item }}.j2"
        dest: "{{ user.home }}/{{ item }}"
        owner: "{{ user.name }}"
        group: "{{ user.group }}"
        mode: '0644'
        backup: yes
      register: wmconfig
      with_items:
        - .config/i3/config
        - .config/i3/modes/resize
        - .config/i3/keybindings
        - .config/i3/appearance
        - .config/i3/window_behavior
        # - .config/i3/window_assignments
        # - .config/i3/autostart

    - name: Set i3status-rs configuration
      template:
        src: "home/{{ item }}.j2"
        dest: "{{ user.home }}/{{ item }}"
        owner: "{{ user.name }}"
        group: "{{ user.group }}"
        mode: '0644'
        backup: yes
      register: wmconfig
      with_items:
        - .config/i3status-rust/config.toml
        - .config/i3status-rust/themes/syncopated.toml

  tags: ['profile']

# - name: Synchronize templates - rofi
#   template:
#     src: "home/{{ item }}.j2"
#     dest: "{{ user.home }}/{{ item }}"
#     owner: "{{ user.name }}"
#     group: "{{ user.group }}"
#     mode: preserve
#     backup: yes
#   with_items:
#     - .config/rofi/config.rasi
#     - .config/rofi/gruvbox-common.rasi
#     - .config/rofi/gruvbox-dark-hard.rasi
#     - .config/rofi/colors/onedark.rasi
#     - .config/rofi/scripts/launcher_main.sh
#     - .config/rofi/scripts/launcher_t1.sh
#     - .config/rofi/scripts/launcher_t4.sh
#     - .config/rofi/launchers/type-1/shared/colors.rasi
#     - .config/rofi/launchers/type-1/shared/fonts.rasi
#     - .config/rofi/launchers/type-1/style-8.rasi
#     - .config/rofi/launchers/type-1/style-10.rasi
#     - .config/rofi/launchers/type-4/shared/colors.rasi
#     - .config/rofi/launchers/type-4/shared/fonts.rasi
#     - .config/rofi/launchers/type-4/style-6.rasi
#   tags: ['profile', 'rofi', 'menus']
