---
# tasks file for alsa

- name: Include distro vars
  include_vars:
    file: vars/{{ ansible_distribution }}.yml
  tags: ['always']

- name: Install alsa packages
  shell: "{{ package_install_command }} {{ item }}"
  with_items:
    - "{{ alsa.packages }}"
  become: False
  tags: ['packages']
