---
# tasks file for alsa
- name: Starting alsa tasks
  debug:
    msg: "Starting alsa tasks"

- name: Install alsa packages
  shell: "{{ package_install_command }} {{ packages.alsa|join(' ') }}"
  become: False
  tags: ['packages']
