---
- hosts: all
  become: False
  gather_subset:
    - hardware
    - network
  vars:
    data: /srv/data
    path:
      - "{{ lookup('env','HOME') }}/.local/bin"
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/bin:{{ path|join(':') }}"
    PKG_CONFIG_PATH: "/usr/share/pkgconfig:/usr/lib/pkgconfig:/usr/local/lib/pkgconfig"

  pre_tasks:
    - name: warn about setting ANSIBLE_HOME
      debug:
        msg: "besure ANSIBLE_HOME is set to this directory"
      tags: ["always"]

    - name: Set datetime
      set_fact:
        datetime: ansible_date_time.epoch
      tags: ["always"]

    - name: Set suffix
      set_fact:
        suffix: ".{{ ansible_date_time.epoch }}.{{ ansible_date_time.date }}@{{ ansible_date_time.time }}~"
      tags: ["always"]

    - name: Ensure data directory exists
      file:
        path: /srv/data
        state: directory
        owner: root
        group: devops
        mode: g+s
      become: True

    - name: Ensure redis data directory exists
      file:
        path: "{{ item }}"
        state: directory
        group: devops
        mode: g+s
      with_items:
        - "{{ data }}/redis/local-data"
      become: True

  tasks:
    - name: "pull redis/redis-stack:latest"
      docker_image:
        name: redis/redis-stack
        tag: latest
        source: pull
      tags: ['image']

    - name: Start Redis Stack server
      docker_container:
        name: redis-stack
        image: redis/redis-stack:latest
        ports:
          - "6379:6379"
          - "8001:8001"
        # env:
          # REDIS_ARGS: "--requirepass mypassword"
        volumes:
          - "{{ data }}/redis/local-data:/data"
        detach: yes
      tags: ['container']
