---
- hosts: workstation
  become: True
  gather_subset:
    - hardware
    - network
  vars:
    homepage_directory: "/usr/share/nginx/html"
    path:
      - "{{ lookup('env','HOME') }}/.local/bin"
  vars_files:
    - ../../vars/intranet.yml
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/bin:{{ path|join(':') }}"
    PKG_CONFIG_PATH: "/usr/share/pkgconfig:/usr/lib/pkgconfig:/usr/local/lib/pkgconfig"

  pre_tasks:

    - name: Set datetime
      set_fact:
        datetime: ansible_date_time.epoch
      tags: ["always"]

    - name: Set suffix
      set_fact:
        suffix: ".{{ ansible_date_time.epoch }}.{{ ansible_date_time.date }}@{{ ansible_date_time.time }}~"
      tags: ["always"]

    # - name: Create homepage folder
    #   file:
    #     path: /usr/share/nginx/
    #     state: directory
    #     owner: root
    #     group: "{{ user.group }}"
    #     mode: '2775'
    #     recurse: True

    # - name: Copy static files
    #   copy:
    #     src: ../files/homepage
    #     dest: /usr/share/nginx/html/
    #     owner: root
    #     group: "{{ user.group }}"
    #     backup: False
    #     # directory_mode:

    - name: Set index.html template
      template:
        src: ../../templates/homepage/index.html.j2
        dest: /usr/share/nginx/html/homepage/index.html
        owner: root
        group: "{{ user.group }}"
        mode: '0664'
        backup: False

  post_tasks:
    - name: Cleanup old backup files
      script: "cleanup.sh"
      when: cleanup is defined
      tags: ["cleanup"]
