---
# defaults file for terminal

# variables loaded in the playbook vars_files will override anything here if there is a conflict

# The default directory permission mode when creating directories using `terminal_directory_definitions`
terminal_directory_default_mode: '0750'

# The default directory owner when creating directories using `terminal_directory_definitions`
terminal_directory_default_owner: "{{ user.name }}"

# The default directory group when creating directories using `terminal_directory_definitions`
terminal_directory_default_group: "{{ user.name }}"

terminal_directory_default_location: "{{ user.home }}"

terminal_directory_default_recurse: False

terminal_directory_definitions:
  - dest: ".config/alacritty"
  - dest: ".config/terminator"
  - dest: ".config/ranger"
  - dest: ".config/ranger/plugins/zoxide"
  - dest: ".config/htop"
  - dest: ".config/kitty"
  - dest: ".config/lnav"
  - dest: ".config/tilda"
  - dest: ".guake"
