---

app:
  install:
    reaper: False
    pulsar: False
    vscode: False
    vamp: False
    mixxx: False
    annotator: False
    soniclineup: False
    touchosc: False
    tony: False


baudline:
  url: "https://www.baudline.com"
  file: "baudline_1.08_linux_x86_64.tar.gz"

jacktrip:
  git: "https://github.com/jacktrip/jacktrip.git"

ocenaudio:
  url:
    debian: "https://www.ocenaudio.com/start_download/ocenaudio_debian9_64.deb"
    fedora: "https://www.ocenaudio.com/downloads/index.php/ocenaudio_centos8.rpm?"

patchage:
  git: "https://gitlab.com/drobilla/patchage.git"

polyphone:
  git: "https://github.com/davy7125/polyphone.git"

qmidinet:
  git: "https://github.com/rncbc/qmidinet.git"

reaper:
  url: "https://www.reaper.fm/files/7.x/"
  file: reaper702_linux_x86_64.tar.xz
  version: v7.02

scala:
  url: "http://www.huygens-fokker.org/software/"
  file: "scala-22-pc64-linux.tar.bz2"

swami:
  git: "https://github.com/swami/swami.git"

libinstpatch:
  git: "https://github.com/swami/libinstpatch.git"

timemachine:
  git: "https://github.com/swh/timemachine.git"

tony:
  url: "https://code.soundsoftware.ac.uk/attachments/download/2617"
  file: "Tony-2.1.1-x86_64.AppImage"

touchosc:
  url: "https://hexler.net/pub/touchosc"
  file: "touchosc-1.2.3.178-linux-x64.zip"
  version: 1.2.3.178

protokol:
  url: "https://hexler.net/pub/protokol/"
  file: "protokol-0.5.1.101-linux-x64.zip"
  version: 0.5.1.101
