---
# defaults file for utils

applications__packages:
  # - antimicrox
  # - calibre
  # - flashfocus
  # - gconf
  # - gksu
  # - jupyter-nbconvert
  # - nwg-wrapper
  # - qutebrowser
  - arandr
  - broot
  - btop
  - calcurse
  - cbonsai
  - dconf
  - devdocs-desktop
  - dunst
  - feh
  - gedit
  - gedit-markdownpreview-git
  - gedit-plugins
  - gedit-smart-home
  - geoclue
  - gnu-free-fonts
  - google-chrome
  - gpick
  - gtk-update-icon-cache
  - gucharmap
  - gummi
  - gvfs-smb
  - imv
  - keepassxc
  - maim
  - metagedit-git
  - mpv
  - nitrogen
  - nvtop
  - obsidian
  - openscad
  - openslide
  - pgmodeler
  - qpdfview
  - radiotray-ng
  - seahorse
  - shotcut
  - sxiv
  - thunar
  - thunar-archive-plugin
  - thunar-volman
  - timeshift
  - vlc
  - wmfocus
  - wordnet-tk
  - zenity
