---

# The default directory permission mode when creating directories using `application_directory_definitions`
application_directory_default_mode: '0755'

# The default directory owner when creating directories using `application_directory_definitions`
application_directory_default_owner: "{{ user.name }}"

# The default directory group when creating directories using `application_directory_definitions`
application_directory_default_group: "{{ user.group }}"

application_directory_default_location: "{{ user.home }}"

application_directory_default_recurse: False

application_directory_definitions:
  - dest: ".sonic-pi/config"
  - dest: ".config/RaySession/session_templates/sound/XXX_SESSION_NAME_XXX.hydrogen"

app:
  install:
    reaper: False
    vamp: False
    mixxx: False
    annotator: False
    soniclineup: False
    touchosc: False
    tony: False

baudline:
  url: "https://www.baudline.com"
  file: "baudline_1.08_linux_x86_64.tar.gz"

jacktrip:
  git: "https://github.com/jacktrip/jacktrip.git"

ocenaudio:
  url:
    debian: "https://www.ocenaudio.com/start_download/ocenaudio_debian9_64.deb"
    fedora: "https://www.ocenaudio.com/downloads/index.php/ocenaudio_centos8.rpm?"

patchage:
  git: "https://gitlab.com/drobilla/patchage.git"

polyphone:
  git: "https://github.com/davy7125/polyphone.git"

qmidinet:
  git: "https://github.com/rncbc/qmidinet.git"

reaper:
  url: "https://www.reaper.fm/files/7.x/"
  file: reaper707_linux_x86_64.tar.xz
  version: v7.07

scala:
  url: "http://www.huygens-fokker.org/software/"
  file: "scala-22-pc64-linux.tar.bz2"

swami:
  git: "https://github.com/swami/swami.git"

libinstpatch:
  git: "https://github.com/swami/libinstpatch.git"

timemachine:
  git: "https://github.com/swh/timemachine.git"

tony:
  url: "https://code.soundsoftware.ac.uk/attachments/download/2617"
  file: "Tony-2.1.1-x86_64.AppImage"

touchosc:
  url: "https://hexler.net/pub/touchosc"
  file: "touchosc-1.2.3.178-linux-x64.zip"
  version: 1.2.3.178

protokol:
  url: "https://hexler.net/pub/protokol/"
  file: "protokol-0.5.1.101-linux-x64.zip"
  version: 0.5.1.101
