---

- block:
    - name: Enable tuned service
      systemd:
        name: tuned
        enabled: yes
        state: started
      register: tuned_service
      ignore_errors: "{{ ansible_check_mode }}"

    # - name: print tuned_service output
    #   debug:
    #     msg: "{{ tuned_service }}"
    #   when:

    - name: Install realtime-modified profile
      copy:
        src: etc/tuned/realtime-modified/tuned.conf
        dest: /etc/tuned/realtime-modified/tuned.conf
        owner: root
        group: root
        mode: '0644'

    - name: Set tuned profile
      shell: |
        tuned-adm profile {{ tuned.profile }}
      register: tuned_profile
      changed_when: tuned_profile.rc != 0
      when: tuned_service.state == 'started'
      ignore_errors: "{{ ansible_check_mode }}"

    # - name: print tuned_service
    #   debug:
    #     msg: "{{ tuned_profile }}"
    #   when:

  tags: ['tuned']
