---

sway:
  packages:
    - autotiling-rs
    - calcurse
    - dex
    - flashfocus
    - mako
    - nm-applet
    - nwg-wrapper
    - playerctl
    - poweralertd
    - swappy
    - sway
    - swaybg
    - swaycwd
    - swayr
    - sworkstyle
    - waybar
    - wf-recorder
    - wlsunset
