---
# roles/pipewire
packages:
  - pipewire
  - pipewire-alsa
  - pipewire-audio
  - pipewire-jack
  - pipewire-pulse
  - gst-plugin-pipewire
  - gst-plugins-bad
  - gst-plugins-bad-libs
  - gst-plugins-base
  - gst-plugins-base-libs
  - gst-plugins-good
  - libpipewire
  - wireplumber
