---
# tasks file for terminal

- name: Terminal Tasks
  debug:
    msg: "Starting terminal tasks"

- name: Ensure terminal directories exist
  file:
    dest: "{{ terminal_directory_default_location }}/{{ item.dest }}"
    state: directory
    owner: "{{ item.owner | default(terminal_directory_default_owner) }}"
    group: "{{ item.group | default(terminal_directory_default_group) }}"
    mode: "{{ item.mode | default(terminal_directory_default_mode) }}"
    recurse: "{{ item.recurse | default(terminal_directory_default_recurse) }}"
  with_items: "{{ terminal_directory_definitions }}"
  check_mode: no

- name: Install terminal packages
  aur:
    use: paru
    name: "{{ packages.terminal }}"
    state: present
  become: False
  tags: ['packages']

- name: Install alacritty template
  template:
    src: etc/skel/.config/alacritty/alacritty.yml.j2
    dest: "{{ user.home }}/.config/alacritty/alacritty.yml"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: True
  tags: ['alacritty']

- name: Install kitty templates
  template:
    src: "etc/skel/.config/kitty/{{ item }}.j2"
    dest: "{{ user.home }}/.config/kitty/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: True
  with_items:
    - kitty.conf
    - current-theme.conf
    - open-actions.conf
    - start.conf
  tags: ['kitty']

- import_tasks:
    file: tui.yml
  tags: ['tui']
