---

- name: Install htop and lnav configs
  template:
    src: "etc/skel/.config/{{ item }}.j2"
    dest: "{{ user.home }}/.config/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  with_items:
    - 'htop/htoprc'
    - 'lnav/checklog.lnav'
  tags: ['htop', 'lnav']

- name: Install ranger configs
  synchronize:
    src: etc/skel/.config/ranger/
    dest: "{{ user.home }}/.config/ranger/"
    recursive: yes
    mode: push
    delete: no
    checksum: yes
    perms: no
    rsync_opts:
      - "--update"
      - "--omit-dir-times"
      - "--progress"
      - "--itemize-changes"
      # - "--chown={{ user.name }}:{{ user.name }}"
      - "--backup"
      - "--suffix={{ suffix }}"
  ignore_errors: "{{ ansible_check_mode }}"
  tags: ['ranger']
