---

de:
display_manager:
window_manager: i3

i3:
  home: "{{ lookup('env','HOME') }}/.config/i3"
  autostart: 'default'
  assignments: 'default'
  workspaces: 'default'
  keybindings: 'default'
  tray_output: 'primary'
