---
# defaults file for audio

# The default directory permission mode when creating directories using `audio_directory_definitions`
audio_directory_default_mode: '0750'

# The default directory owner when creating directories using `audio_directory_definitions`
audio_directory_default_owner: root

# The default directory group when creating directories using `audio_directory_definitions`
audio_directory_default_group: root

audio_directory_default_recurse: False

audio_directory_definitions:
  - dest: /etc/security/limits.d
  - dest: /etc/sysctl.d
  - dest: /etc/tuned/realtime-modified
  - dest: /usr/local/share/vamp

tune_for_realtime: False

cpupower:
  governor: powersave
  perf_bias: 6

tuned:
  profile: powersave

enable_jack: False
enable_pipewire: False
enable_pulseaudio: False

# defaults file for jack

jack_control:
  dps:
    device: hw:0
    capture: none
    playback: none
    rate: 48000
    period: 1024
    nperiods: 2
    hwmon: False
    hwmeter: False
    duplex: True
    softmode: False
    monitor: True
    dither: n
    shorts: False
    mididriver: seq
  eps:
    driver: alsa
    name: default
    realtime: True
    realtimepriority: 89
    temporary: False
    verbose: False
    # client-timeout: Client timeout limit in milliseconds. (sint:notset:0:0)
    # clock-source: Clocksource type : c(ycle) | h(pet) | s(ystem). (uint:notset:0:0)
    port-max: 2048
    replaceregistry: False
    sync: False
    # self-connect-mode: Self connect mode. (char:notset: : )
    # slave-drivers: Slave drivers to use (str:notset::)


# defaults file for pulseaudio

# The default directory permission mode when creating directories using `pulse_directory_definitions`
pulse_directory_default_mode: '0755'

# The default directory owner when creating directories using `pulse_directory_definitions`
pulse_directory_default_owner: "{{ user.name }}"

# The default directory group when creating directories using `pulse_directory_definitions`
pulse_directory_default_group: "{{ user.group }}"

pulse_directory_default_location: "{{ user.home }}"

pulse_directory_default_recurse: False

pulse_directory_definitions:
  - dest: ".config/pulse"
    mode: "0700"
