---
# tasks file for lightdm

- block:
    - name: Install lightdm
      aur:
        use: auto
        name: lightdm
        state: present
      become: False

    # https://github.com/NoiSek/Aether

    - name: Ensure group autologin exists
      group:
        name: autologin
        state: present
        system: yes

    - name: Add user to autologin group
      user:
        name: "{{ user.name }}"
        groups: autologin
        append: yes

    - name: Install xsession file to /etc/lightdm/xsession
      copy:
        src: etc/lightdm/Xsession
        dest: /etc/lightdm/Xsession
        directory_mode: yes
        owner: root
        group: root
        mode: '0755'

    - name: Update lightdm.conf
      template:
        src: etc/lightdm/lightdm.conf.j2
        dest: /etc/lightdm/lightdm.conf
        mode: '644'
        owner: root
        group: root
        backup: yes

    - name: Update pam
      copy:
        src: "etc/pam.d/{{ item }}"
        dest: "/etc/pam.d/{{ item }}"
        mode: '0644'
        backup: yes
      with_items:
        - lightdm-autologin
        - login
        - passwd
      tags: ['pam']

  notify: "enable and restart lightdm service"
  when: login.lightdm|default(false)|bool == True
  tags: ['lightdm']
