---

- name: Starting common tasks
  debug:
    msg: "Starting common tasks"

- name: Include distro vars
  include_vars:
    file: vars/{{ ansible_distribution }}.yml
  tags: ['always']

- import_tasks:
    file: sshd.yml
  tags: ['common', 'sshd']

- import_tasks:
    file: dirs.yml
  tags: ['common', 'dirs']

- import_tasks:
    file: sudoers.yml
  tags: ['user', 'sudoers']

- import_tasks:
    file: repos.yml
  tags: ['repo', 'packages']

- import_tasks:
    file: updatedb.yml
  tags: ['common', 'updatedb']

- import_tasks:
    file: zram.yml
  tags: ['common', 'zram']

- import_tasks:
    file: grub.yml
  tags: ['common', 'grub']

- import_tasks:
    file: autofs.yml
  tags: ['common', 'autofs']

- import_tasks:
    file: scripts.yml
  tags: ['common', 'scripts']
