---
# tasks file for docker

- name: Starting docker tasks
  debug:
    msg: "Starting docker tasks"

- name: Include distro vars
  include_vars:
    file: vars/{{ ansible_distribution }}.yml
  tags: ['always']

- name: Starting docker tasks
  debug:
    msg: "Starting docker tasks"

- import_tasks:
    file: setup.yml
  tags: ['setup']
