---
# tasks file for docker

- name: Docker Tasks
  debug:
    msg: "Starting docker tasks"

# https://discuss.python.org/t/getting-requirements-to-build-wheel-did-not-run-successfully-exit-code-1/30365/2
- block:
    - name: Echo the pip constraint variable into a file
      shell: echo "Cython<3" > cython_constraint.txt
      args:
        chdir: /tmp/

    - name: Install python docker modules
      pip:
        name: "{{ item }}"
        executable: pip3
        state: present
        extra_args: --break-system-packages
      with_items:
        - docker
        - docker-compose
      environment:
        PIP_CONSTRAINT: "/tmp/cython_constraint.txt"
      when: distribution == 'Archlinux' or distribution == 'EndeavourOS'

    - name: Install python docker modules
      pip:
        name: "{{ item }}"
        executable: pip3
        state: present
      with_items:
        - docker
        - docker-compose
      when: distribution == 'Fedora'

  tags: ['packages']

- name: Ensure docker data directory exists
  file:
    path: "{{ docker.storage }}"
    state: directory
    owner: root
    group: root

- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

#TODO: add failed_when logic
- name: Add user to docker group
  user:
    name: "{{ item.name  }}"
    groups: docker
    append: yes
  with_items:
    - "{{ users }}"
  check_mode: yes
  # register: dockergroup
  # failed_when: "not 'Group docker does not exist' in dockergroup.msg"
  tags: ['groups']

- import_tasks:
    file: setup.yml
  tags: ['setup']
