---
# tasks file for sway

- name: Include distro vars
  include_vars:
    file: vars/{{ ansible_distribution }}.yml
  tags: ['always']

- name: check vars
  debug:
    msg: "{{ theme.colors }}"

- name: check role
  debug:
    msg: "sway role!"
