---
autologin: True

bluetooth: False

app:
  install:
    reaper: True
    pulsar: True
    vscode: True
    vamp: True
    mixxx: True
    annotator: True
    soniclineup: True
    touchosc: True
    tony: True

desktop:
  wm: i3
  terminal: "kitty"
  terminal_alt: "alacritty"
  browser: "google-chrome-stable"
  audio: "jack"

# x:
#   autostart:
#     - "jacktrip -s -n 4 -q auto -b 24 -D --udprt &"

i3:
  autostart: 'default'
  tray_output: 'primary'
  assignments: 'default'
  workspaces: 'default'
  keybindings: 'default'
