---
autologin: True

bluetooth: True

repos:
  chaotic: False
  syncopated: True

share:
  nfs:
    parent: "{{ user.home }}"
    exports:
      - LLMOS

app:
  install:
    reaper: True
    pulsar: True
    vscode: True
    vamp: True
    mixxx: True
    annotator: True
    soniclineup: True
    touchosc: True
    tony: True

cpupower:
  governor: performance
  perf_bias: 0

tuned:
  profile: powersave

docker:
  service: "enabled"
  storage: /var/lib/docker
  nvidia: False

desktop:
  dm: False
  wm: i3
  terminal: "kitty"
  terminal_alt: "alacritty"
  browser: "google-chrome-stable"
  audio: "jack"
  barrier:
    client:
      name: tinybot
      server: "[soundbot]:24800"

x:
  autostart:
    - bash ~/.screenlayout/tinybot.sh

i3:
  autostart:
    - "ray-daemon --session-root ~/Public/NetworkSessions -p 7777"
  tray_output: "primary"
  assignments: "default"
  workspaces:  "default"
  keybindings: "default"

# network_interfaces:
#   - device: eth0
#     type: ethernet
#     ifname: eth0
#     conn_name: eth0
#     mac: 68:1d:ef:2a:ac:47
#     ip4: 192.168.41.43/24
#     gw4: 192.168.41.1
#     dns4:
#       - 192.168.41.41
#       - 192.168.41.1
#     dns4_search: syncopated.net
#     autoconnect: True
#     state: present
#     method4: manual
#   - device: eth1
#     type: ethernet
#     ifname: eth1
#     conn_name: eth1
#     mac: 68:1d:ef:2a:b4:03
#     ip4: 192.168.36.2/24
#     autoconnect: True
#     state: present
#     method4: manual
#   - device: wlan0
#     type: wifi
#     ifname: wlan0
#     conn_name: wlan0
#     ssid: "invisiblemagic"
#     mac: c2:03:79:0d:7d:b3
#     autoconnect: False
#     state: present
#     method4: disabled

host:
  xorg:
    video:
      # intel:
      - intel-gpu-tools
      - intel-media-driver
      - intel-ucode
      - libva-intel-driver
      - libva-mesa-driver
      # - libvdpau-va-gl-i965
      - vulkan-headers
      - vulkan-icd-loader
      - vulkan-intel
      - xf86-video-intel
      # opengl:
      - libva-utils
      - libvdpau-va-gl
      - libva-mesa-driver
      - mesa
      - mesa-utils
      - mesa-vdpau
      - vdpauinfo
      # opencl:
      - opencl-clover-mesa
      - opencl-rusticl-mesa
