---

- name: Check repository version
  shell: "paru -Si code | grep -w 'extra/code' | awk '{print $2}' | sed 's/-1$//' | xargs"
  register: desired_version
  changed_when: false

- name: Get installed application version
  shell: "code --version | head -1 |awk '{print $1}'"
  register: current_version
  changed_when: false

- block:
    - name: Install vscode
      aur:
        use: auto
        name: code
        state: present

    - name: Check currently installed extensions
      shell: code --list-extensions
      register: installed_extensions
      changed_when: installed_extensions.rc != 0
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Set list of extensions to install
      set_fact:
        _extensions: "{{ vscode.extensions|difference(installed_extensions.stdout) }}"

    - name: Install VSCode extensions
      shell: "code --install-extension {{ item }}"
      with_items:
        - "{{ _extensions }}"
      when: _extensions | length > 0

  rescue:
    - name: Handle installation failure
      debug:
        msg: "Failed to install VSCode extension: {{ item }}"
      loop: "{{ ansible_failed_result.results | map(attribute='item') | list }}"

  always:
    - name: Continue execution
      debug:
        msg: "Continuing with playbook execution"

  become: False
