---

- name: Placeholder for /etc/environment
  copy:
    src: etc/environment
    dest: /etc/environment
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Adjust /etc/profile
  copy:
    src: "etc/profile"
    dest: "/etc/profile"
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name:  Install .aliases and .profile
  template:
    src: "etc/skel/{{ item }}.j2"
    dest: "/etc/skel/{{ item }}"
    owner: root
    group: root
    mode: '0644'
    backup: True
  with_items:
    - .aliases
    - .profile
  tags: ['profile']
