---

# - name: show expected_value
#   debug:
#     msg: "{{ expected_value }}"
#   tags: ['testing']

- name: Base Tasks
  debug:
    msg: "Starting base tasks"
  register: expected_value

# - name: show expected_value
#   debug:
#     msg: "{{ expected_value }}"
#   tags: ['testing']

- import_tasks:
    file: sudoers.yml
  tags: ['sudoers']

- name: Ensure root directories exist
  file:
    dest: "{{ item.dest }}"
    state: directory
    owner: "{{ item.owner | default(root_directory_default_owner) }}"
    group: "{{ item.group | default(root_directory_default_group) }}"
    mode: "{{ item.mode | default(root_directory_default_mode) }}"
    recurse: "{{ item.recurse | default(root_directory_default_recurse) }}"
  with_items: "{{ root_directory_definitions }}"

- import_tasks:
    file: environment.yml
  tags: ['env', 'profile']

- import_tasks:
    file: xdg.yml
  tags: ['xdg', 'profile']

- import_tasks:
    file: sshd.yml
  tags: ['sshd']

- import_tasks:
    file: repos.yml
  tags: ['repo', 'packages']

- import_tasks:
    file: updatedb.yml
  tags: ['updatedb']

- import_tasks:
    file: zram.yml
  tags: ['zram']

- name: Set video modules in mkinitcpio
  template:
    src: etc/mkinitcpio.conf.j2
    dest: /etc/mkinitcpio.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  register: mkinitcpio_conf
  tags: ['mkinitcpio']

- name: use shell to do stuff
  shell: mkinitcpio -P
  when: mkinitcpio_conf.changed
  tags: ['mkinitcpio']

- import_tasks:
    file: grub.yml
  tags: ['grub']

- import_tasks:
    file: autofs.yml
  tags: ['autofs']

- name: Install utility scripts
  synchronize:
    src: usr/local/bin/
    dest: /usr/local/bin/
    recursive: yes
    mode: push
    delete: no
    checksum: yes
    perms: no
    rsync_opts:
      - "--update"
      - "--omit-dir-times"
      - "--backup"
      - "--suffix={{ suffix }}"
      - "--chmod=0755"
  ignore_errors: "{{ ansible_check_mode }}"
  tags: ['always']
