---

- name: Set sshd config
  template:
    src: etc/ssh/sshd_config.j2
    dest: /etc/ssh/sshd_config
    backup: True
  register: sshd_config

- name: Restart sshd
  service:
    name: sshd
    state: restarted
    enabled: True
  when: sshd_config.changed
