---

- name: use shell to do stuff
  shell: |
    mkdir -pv pipewire

    mkdir -pv wireplumber/{scripts,wireplumber.conf.d}
  args:
    chdir: "{{ user.home }}/.config"
  become: False

- name: Copy default PipeWire configuration files
  copy:
    src: "/usr/share/pipewire/"
    dest: "{{ user.home }}/.config/pipewire/"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    remote_src: yes
  notify: Restart PipeWire

- name: Create custom JSON configuration for sound card
  copy:
    dest: "/home/{{ pipewire_user }}/.config/wireplumber/wireplumber.conf.d/51-disable-suspension.conf"
    content: |
      {
        "monitor.alsa.rules": [
          {
            "matches": [
              { "node.name": "~alsa_input.*" },
              { "node.name": "~alsa_output.*" }
            ],
            "actions": {
              "update-props": {
                "session.suspend-timeout-seconds": 0
              }
            }
          }
        ]
      }
    owner: "{{ pipewire_user }}"
    group: "{{ pipewire_user }}"
  notify: Restart WirePlumber

- name: Create filter-chain configuration for noise reduction
  copy:
    dest: "/home/{{ pipewire_user }}/.config/pipewire/filter-chain.conf.d/noise-reduction.conf"
    content: |
      {
        "name": "noise_reduction",
        "description": "Noise Reduction Filter Chain",
        "filter.graph": [
          {
            "type": "ladspa",
            "name": "noise_reduction",
            "plugin": "{{ noise_reduction_plugin }}",
            "label": "{{ noise_reduction_label }}",
            "control": {
              "VAD Threshold": {{ vad_threshold }}
            }
          }
        ],
        "capture.props": {
          "node.name": "alsa_input.usb-*.*",
          "media.class": "Audio/Source"
        },
        "playback.props": {
          "node.name": "filtered_noise_reduction",
          "media.class": "Audio/Sink"
        }
      }
    owner: "{{ pipewire_user }}"
    group: "{{ pipewire_user }}"
  notify: Restart PipeWire

- name: Enable and start PipeWire services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    scope: user
  loop:
    - pipewire
    - pipewire-pulse
    - wireplumber
