---
# tasks file for pipewire

- name: Pipewire Tasks
  debug:
    msg: "Starting pipewire tasks"


- block:
    - name: Stop pipewire service
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
        scope: user
      with_items:
        - wireplumber.service
        - pipewire-pulse.service
        - pipewire-pulse.socket
        - pipewire.service
        - pipewire-session-manager.service
        - pipewire.socket
      environment:
        XDG_RUNTIME_DIR: "/run/user/1000"
      become: False
      register: servicestat
      failed_when: (servicestat.state is defined and servicestat.state != 'stopped') or (servicestat.msg is defined and not 'Could not find the requested service' in servicestat.msg and servicestat.rc != 0)
      ignore_errors: "{{ ansible_check_mode }}"

    # - name: debug
    #   debug:
    #     msg: "{{ servicestat.results[0] }}"

    - name: Remove pipewire packages
      pacman:
        name: "{{ packages.pipewire }}"
        state: absent
        force: yes
        extra_args: --noconfirm
      register: uninstall
      failed_when: uninstall.packages | length > 0
      tags: ['packages']

    - name: Install pipewire and wireplumber libs
      aur:
        use: paru
        name: "{{ item }}"
        state: present
      loop:
        - libpipewire
        - libwireplumber
      become: False
      ignore_errors: "{{ ansible_check_mode }}"
      tags: ['packages']

  when:
    - initialInstall|default(false)|bool == True
    - audio == 'jack'
