---

- name: Create folders for user config
  shell: |
    mkdir -pv pipewire

    mkdir -pv wireplumber/{scripts,wireplumber.conf.d}
  args:
    chdir: "{{ user.home }}/.config"
  become: False

- name: Copy default PipeWire configuration files
  copy:
    src: "/usr/share/pipewire/"
    dest: "{{ user.home }}/.config/pipewire/"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    remote_src: yes
  notify: Restart PipeWire

- name: Create custom JSON configuration for sound card
  copy:
    dest: "/home/{{ pipewire_user }}/.config/wireplumber/wireplumber.conf.d/51-disable-suspension.conf"
    content: |
      {
        "monitor.alsa.rules": [
          {
            "matches": [
              { "node.name": "~alsa_input.*" },
              { "node.name": "~alsa_output.*" }
            ],
            "actions": {
              "update-props": {
                "session.suspend-timeout-seconds": 0
              }
            }
          }
        ]
      }
    owner: "{{ pipewire_user }}"
    group: "{{ pipewire_user }}"
  notify: Restart WirePlumber

https://www.perplexity.ai/search/let-s-work-on-migrating-from-j-_TZudN6TQbS1inb0KNHW4g

https://docs.pipewire.org/page_module_filter_chain.html

- name: Enable and start PipeWire services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    scope: user
  loop:
    - pipewire
    - pipewire-pulse
    - wireplumber
