---
# tasks file for pipewire

- name: Include distro vars
  include_vars:
    file: vars/{{ ansible_distribution }}.yml
  tags: ['always']

- name: Starting pipewire tasks
  debug:
    msg: "Starting pipewire tasks"

- import_tasks:
    file: uninstall.yml
  when: use_pipewire|default(true)|bool == False

- import_tasks:
    file: install.yml
  when: use_pipewire|default(true)|bool
