---

- name: stop pipewire service
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    scope: user
  with_items:
    - wireplumber.service
    - pipewire-pulse.service
    - pipewire-pulse.socket
    - pipewire.service
    - pipewire-session-manager.service
    - pipewire.socket
  environment:
    XDG_RUNTIME_DIR: "/run/user/1000"
  become: False
  register: servicestat
  failed_when: (servicestat.state is defined and servicestat.state != 'stopped') or (not 'Could not find the requested service' in servicestat.msg and servicestat.rc != 0)
  ignore_errors: "{{ ansible_check_mode }}"

# - name: debug
#   debug:
#     msg: "{{ servicestat.results[0] }}"

- name: UnInstall pipewire packages
  shell: "{{ package_uninstall_command }} {{ pipewire.packages|join(' ') }}"
  become: False
  register: uninstall
  changed_when: uninstall.rc == 0
  failed_when: "'error: failed to prepare transaction' in uninstall.stderr and uninstall.rc != 0"

- name: Install pipewire and wireplumber libs
  shell: "{{ package_install_command }} libpipewire libwireplumber"
  become: False
  ignore_errors: "{{ ansible_check_mode }}"
