# tasks file for jack

- name: Include distro vars
  include_vars:
    file: vars/{{ ansible_distribution }}.yml
  tags: ['always']

- name: Starting jack tasks
  debug:
    msg: "Starting jack tasks"

- block:

    - import_tasks:
        file: uninstall.yml
      when: use_pipewire|default(false)|bool == True

    - import_tasks:
        file: install.yml
      when: use_pipewire|default(false)|bool == False

  check_mode: no
  tags: ['packages']
