---

- name: Install jack packages
  shell: "{{ package_uninstall_command }} {{ jack.packages|join(' ') }}"
  become: False
  register: uninstall
  changed_when: uninstall.rc == 0
  failed_when: "'error: failed to prepare transaction' in uninstall.stderr and uninstall.rc != 0"
  tags: ['packages']
