---
- hosts: all
  become: True
  gather_subset:
    - hardware
    - network
  vars:
    path:
      - "{{ lookup('env','HOME') }}/.local/bin"
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/bin:{{ path|join(':') }}"
    PKG_CONFIG_PATH: "/usr/share/pkgconfig:/usr/lib/pkgconfig:/usr/local/lib/pkgconfig"

  roles:
    - role: lightdm
      tags: ["lightdm"]

    - role: x
      tags: ["x"]

    - role: i3
      tags: ["i3"]

    - role: desktop
      tags: ["desktop"]

    - role: applications
      tags: ["applications"]

    - role: theme
      tags: ["theme"]
