---
- hosts: all
  become: True
  gather_facts: yes
  vars:
    path:
      - "{{ lookup('env','HOME') }}/.asdf/bin"
      - "{{ lookup('env','HOME') }}/.local/bin"
      - "{{ lookup('env','HOME') }}/Utils/bin"
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/bin:{{ path|join(':') }}"
    PKG_CONFIG_PATH: "/usr/share/pkgconfig:/usr/lib/pkgconfig:/usr/local/lib/pkgconfig"
    ZSH: "/usr/share/oh-my-zsh"
    DISPLAY: ":0"
  # variables from vars_files are available starting here...
  pre_tasks:
    # the task will run if `check_mode` to 'no'
    - name: Register timestamp
      shell: "date +'%s.%Y-%m-%d@%H:%M:%S~'"
      register: timestamp
      check_mode: no
      tags: ["always"]

    - name: Set suffix
      set_fact:
        suffix: "{{ timestamp.stdout_lines[0] }}"
      tags: ["always"]

    - name: Set distro name
      set_fact:
        ansible_distribution: "{{ distro }}"
      when: distro is defined
      tags: ["always", "testing"]

    - name: Display ansible_distribution
      debug:
        msg: |
          The host {{ inventory_hostname }} has {{ ansible_distribution }} installed,
          which belongs to the {{ ansible_os_family }} OS family
      tags: ['always']

    - name: Symlink /etc/os-release to /etc/system-release
      file:
        src: /etc/os-release
        dest: /etc/system-release
        state: link

    - name: Set admin group name
      set_fact:
        admin_group: wheel
      tags: ["always"]

    # to allow for ansible pipelining functionality
    # https://docs.ansible.com/ansible/2.4/intro_configuration.html#pipelining
    # while this requirement was removed in RHEL, many other distros leave this option enabled
    - name: Disable requiretty for user so automation can run without interruption
      lineinfile:
        dest: /etc/sudoers
        regexp: "^Defaults    requiretty"
        line: "Defaults:{{ user.name }}    !requiretty"
        backrefs: yes
        backup: yes
        validate: 'visudo -cf %s'
      when: user.name != 'root'
      tags: ['sudoers']

  roles:

    - role: base
      tags: ["base"]

    - role: user
      tags: ["user"]

    - role: shell
      tags: ["shell"]

    - role: sudoers
      tags: ["sudoers"]

    - role: ruby
      tags: ["ruby"]

    - role: networking
      tags: ["networking"]

- hosts: virt
  become: True
  gather_facts: yes
  vars:
    path:
      - "{{ lookup('env','HOME') }}/.asdf/bin"
      - "{{ lookup('env','HOME') }}/.local/bin"
      - "{{ lookup('env','HOME') }}/Utils/bin"
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/bin:{{ path|join(':') }}"

  roles:

    - role: docker
      when: use_docker == True
      tags: ["docker"]

    - role: libvirt
      when: use_libvirt == True
      tags: ["libvirt"]

- hosts: workstation
  become: True
  gather_facts: yes
  vars:
    path:
      - "{{ lookup('env','HOME') }}/.asdf/bin"
      - "{{ lookup('env','HOME') }}/.local/bin"
      - "{{ lookup('env','HOME') }}/Utils/bin"
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/bin:{{ path|join(':') }}"

  roles:

    - role: input-remapper
      tags: ["input-remapper"]

    - role: x11
      tags: ["x11"]

    - role: terminal
      tags: ["terminal"]

    - role: xdg
      tags: ["xdg"]

    - role: rofi
      tags: ["rofi"]

    - role: i3
      tags: ["i3"]

    - role: applications
      tags: ["applications"]

    - role: barrier
      tags: ["barrier"]

    - role: pulsar
      tags: ["pulsar"]

    - role: vscode
      tags: ["vscode"]

    - role: deadbeef
      tags: ["deadbeef"]

    - role: obs-studio
      tags: ["obs-studio"]

    - role: theme
      tags: ["theme"]

- hosts: daw
  become: True
  gather_facts: yes
  vars:
    path:
      - "{{ lookup('env','HOME') }}/.asdf/bin"
      - "{{ lookup('env','HOME') }}/.local/bin"
      - "{{ lookup('env','HOME') }}/Utils/bin"
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/bin:{{ path|join(':') }}"

  roles:

    - role: tuning
      tags: ["tunig"]

    - role: alsa
      tags: ["alsa"]

    - role: jackd
      tags: ["jackd"]

    - role: pulseaudio
      tags: ["pulseaudio"]

    - role: pipewire
      tags: ["pipewire"]

    - role: daw
      tags: ["daw"]


  post_tasks:
    - name: Cleanup old backup files
      script: "{{ lookup('env','HOME') }}/Utils/bin/cleanup.sh"
      when: cleanup is defined
      tags: ["cleanup"]

    - block:
        - name: Reboot the host
          reboot:
            msg: "Reboot initiated by Ansible"
            connect_timeout: 5
            reboot_timeout: 300
            pre_reboot_delay: 0
            post_reboot_delay: 30
            test_command: uptime

      rescue:
        # Do not assume the inventory_hostname is resolvable and delay 10 seconds at start
        - name: Wait 600 seconds for port 22 to become open"
          ansible.builtin.wait_for:
            port: 22
            host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
            delay: 10
            timeout: 600
          connection: local

      when: reboot is defined
      tags: ['reboot']


    - name: Reboot successful
      debug:
        msg: "Reboot successful"
      tags: ['reboot']
