---
- hosts: workstation
  become: True
  gather_facts: yes
  vars:
    path:
      - "{{ lookup('env','HOME') }}/.asdf/bin"
      - "{{ lookup('env','HOME') }}/.local/bin"
      - "{{ lookup('env','HOME') }}/Utils/bin"
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/bin:{{ path|join(':') }}"

  roles:

    - role: input-remapper
      tags: ["input-remapper"]

    - role: x11
      tags: ["x11"]

    - role: terminal
      tags: ["terminal"]

    - role: xdg
      tags: ["xdg"]

    - role: rofi
      tags: ["rofi"]

    - role: i3
      tags: ["i3"]

    - role: barrier
      tags: ["barrier"]

    - role: pulsar
      tags: ["pulsar"]

    - role: vscode
      tags: ["vscode"]

    - role: deadbeef
      tags: ["deadbeef"]

    - role: obs-studio
      tags: ["obs-studio"]

    - role: theme
      tags: ["theme"]
