---
# defaults file for utils

packages:
  # - antimicrox
  - arandr
  - asciiquarium-git
  - asciiquarium-transparent-git
  - audiofile
  - autotiling-rs
  - calibre
  - cbonsai
  - chromaprint
  - crossguid
  - devdocs-desktop
  - eza
  - faac
  - faad2
  - gedit-markdownpreview-git
  - gedit-plugins
  - gedit-smart-home
  - geoclue
  - google-chrome
  - gpick
  - grsync
  - gummi
  - gvfs-smb
  - jupyter-nbconvert
  - keepassxc
  - libcyaml
  - libgit2
  - libgit2-glib
  - libvips
  - libvoikko
  - links
  - metagedit-git
  - micro
  - nitrogen-git
  - noise-repellent
  - nwg-wrapper
  - nyan-lang-git
  - obsidian
  - octopi
  - openscad
  - openslide
  - pgmodeler
  - pgvector
  - platformfolders
  - postgresql-libs
  - python-conda-package-handling
  - python-j2cli
  - python-pagelabels
  - python-pympler
  - python-sphinx-intl
  - python-sphinxcontrib-svg2pdfconverter
  - qpdf
  - qpdfview
  - qutebrowser
  - radiotray-ng
  - redshift
  - rxvt-unicode
  - seahorse
  - shotcut
  - speech-dispatcher
  - stunnel
  - sworkstyle
  - teiler-git
  - texlive-basic
  - texlive-bin
  - texlive-coffee-stains
  - texlive-doc
  - texlive-fontsextra
  - texlive-fontsrecommended
  - texlive-latex
  - texlive-latexextra
  - texlive-latexrecommended
  - texlive-pictures
  - texlive-xetex
  - thunar
  - thunar-archive-plugin
  - thunar-volman
  - timeshift
  - vlc
  - wmfocus
  - wordnet-tk
  - yadm
  - zenity
