---

autologin: True

nfs:
  parent: "{{ user.home }}"
  exports:
    - Archive
    - Workspace

app:
  install:
    reaper: True
    pulsar: True
    vscode: True
    vamp: True
    mixxx: True
    annotator: True
    soniclineup: True
    touchosc: True
    tony: True

docker:
  service:
    enabled: True
  storage: /var/lib/docker
  nvidia: False

use_bluetooth: True

desktop:
  wm: i3
  terminal: "kitty"
  terminal_alt: "alacritty"
  browser: "google-chrome-stable"
  audio: "jack"
  barrier:
    client:
      name: tinybot.syncopated.net
      server: '[soundbot.syncopated.net]:24800'

x:
  autostart:
    - xrandr --output HDMI-1 --auto

i3:
  autostart:
    - "ray-daemon --session-root ~/NetworkSessions -p 7777"
    # - "jacktrip -c tinybot.soundbot.net -n 4 -q auto -b 24 -D --udprt &"
    # - "ray-daemon --session-root ~/NetworkSessions -p 7777"
  tray_output: 'HDMI-1'
  assignments: 'default'
  workspaces: 'default'
  keybindings: 'default'

# monitors:
#   - id: 1
#     output: "DP1-1"
#     mode: "2560x1440"
#     pos: "0x0"
#     rotate: "normal"
#     workspaces: [1,2,3,4,5,6,7,8,9,0] # bind workspace to a specific monitor

# network:
#   interfaces:
#     enp2s0:
#       type: ethernet
#       ifname: enp2s0
#       conn_name: enp2s0
#       mac: 68:1d:ef:2a:b4:03
#       ip4: 192.168.41.26
#       gw4: 192.168.41.1
#       dns4: 192.168.41.1
#       dns4_search: syncopated.net
#       autoconnect: True
#       state: present
#       method4: manual
#     enp3s0:
#       type: ethernet
#       ifname: enp3s0
#       conn_name: audio
#       mac: 68:1d:ef:2a:ac:47
#       ip4: 192.168.36.1
#       autoconnect: True
#       state: present
#       method4: manual
#     wlan0:
#       type: wifi
#       ifname: wlan0
#       conn_name: wlan0
#       mac: c2:03:79:0d:7d:b3
#       autoconnect: False
#       state: present
#       method4: disabled
host:
  xorg:
    video:
    # intel:
      - intel-gpu-tools
      - intel-media-driver
      - intel-ucode
      - libva-intel-driver
      - libva-mesa-driver
      # - libvdpau-va-gl-i965
      - vulkan-headers
      - vulkan-icd-loader
      - vulkan-intel
      - xf86-video-intel
    # opengl:
      - libva-utils
      - libvdpau-va-gl
      - libva-mesa-driver
      - mesa
      - mesa-utils
      - mesa-vdpau
      - vdpauinfo
    # opencl:
      - opencl-clover-mesa
      - opencl-rusticl-mesa
