---

- name: Install asdf
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "{{ user.home }}/.asdf"
    recursive: yes
    accept_hostkey: yes
    update: no
    force: no
    version: v0.13.1
  check_mode: no
  become: False

# add asdf plugin to oh-my-zsh plugins var
- name: Add asdf plugin to oh-my-zsh plugins
  lineinfile:
    path: "{{ user.home }}/.zshrc"
    regexp: "^plugins="
    line: "plugins=(asdf ansible bundler docker-compose copypath fd fzf ripgrep zsh-navigation-tools ruby history systemd web-search)"
    insertafter: 'ZSH_CUSTOM="/usr/local/share/zsh"'
    firstmatch: True
  become: False

- name: Set default-gems
  template:
    src: home/.default-gems.j2
    dest: "{{ user.home }}/.default-gems"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
  become: False

- name: Install ruby plugin
  shell: |
    source ~/.zshrc && \
    asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git && \
    asdf install ruby 3.1.4 && \
    asdf global ruby 3.1.4
  args:
    executable: /bin/zsh
  become: False
