---
# tasks file for ruby
- name: Ruby Tasks
  debug:
    msg: "Starting ruby tasks"

- name: Load a variable file based on the OS type, or a default if not found. the file.
  include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        # - '{{ansible_distribution}}.yml'
        - '{{ansible_os_family}}.yml'
        # - Archlinux.yml
        # - main.yml
      paths:
        - 'vars'
  tags: ['packages']

- setup:
- debug:
    msg: "{{ packages }}"

# by default /etc/gemrc is set to --user-install
# set --no-user-install in /root/.gemrc
# to install gems system wide using sudo
- name: Set --no-user-install in /root/.gemrc
  copy:
    content: |
      gem: --no-user-install --no-document
    dest: "/root/.gemrc"
    owner: root

- name: Set --user-install in /home/user/.gemrc
  copy:
    content: |
      gem: --user-install
    dest: "{{ user.home }}/.gemrc"
    owner: "{{ user.name }}"

- name: Set --no-user-install in /etc/gemrc
  copy:
    content: |
      gem: --user-install
    dest: "/etc/gemrc"
    owner: root

- name: Install Ruby dev packages
  package:
    name: "{{ packages }}"
    state: present
  tags: ['packages']

- import_tasks:
    file: asdf.yml
  tags: ['asdf']

- name: Install ruby profile.d script
  template:
    src: etc/profile.d/ruby.sh.j2
    dest: /etc/profile.d/ruby.sh
    owner: root
    group: root
    mode: '0755'
    backup: True

# - name: update system bundler
#   shell: gem update --system 3.4.21
#
# - name: gather list of installed gems
#   shell: "gem list | awk '{ print $1 }'"
#   become: False
#   register: gemlist
#   changed_when: gemlist.rc != 0
#   ignore_errors: "{{ ansible_check_mode }}"
#
# - name: set list of gems to install
#   set_fact:
#     ruby__gems: "{{ gems|difference(gemlist.stdout) }}"
#
# - name: install ruby gems
#   shell: "gem install {{ item }}"
#   with_items:
#     - "{{ ruby__gems }}"
#   when: ruby__gems | length > 0
