app:
  description: "Analyze the provided example, explaining how its functional and generative\
    \ grammars contribute to its pragmatic intention. Using a syntax tree, Generate\
    \ a variant of the example that uses part of speech tags instead of the literal\
    \ concepts\n<example>\n<input>\n<article_title> The Impact of Climate Change on\
    \ Coastal Cities </article_title>\n<article_outline> \n  1. Introduction\n  2.\
    \ Rising Sea Levels\n  3. Increased Storm Frequency\n  4. Conclusion\n</article_outline>\n\
    </input>\n<output>\n [\n    {\n      \"section\": \"Introduction\",\n      \"\
    bullets\": \"1. Overview of climate change effects on coastal cities 2. Importance\
    \ of understanding these impacts\"\n    },\n    {\n      \"section\": \"Rising\
    \ Sea Levels\",\n      \"bullets\": \"1. Causes of rising sea levels 2. Effects\
    \ on coastal infrastructure and communities3. Examples of affected cities\"\n\
    \    },\n   {\n      \"section\": \"Increased Storm Frequency\",\n      \"bullets\"\
    : \"1. Link between climate change and storm frequency 2. Impact of more frequent\
    \ and severe storms on coastal areas 3. Case studies of recent storms\"\n    },\
    \ \n   {\n      \"section\": \"Conclusion\",\n      \"bullets\": \"1. Summary\
    \ of key points 2. The urgency of addressing climate change 2. Call to action\
    \ for policymakers and communities\"\n    }\n  ]\n</output>\n</example>\n"
  icon: "\U0001F916"
  icon_background: '#FFEAD5'
  mode: completion
  name: Example Text To Grammars
model_config:
  agent_mode:
    enabled: false
    max_iteration: 5
    strategy: function_call
    tools: []
  annotation_reply:
    enabled: false
  chat_prompt_config: {}
  completion_prompt_config: {}
  dataset_configs:
    datasets:
      datasets: []
    retrieval_model: single
  dataset_query_variable: ''
  external_data_tools: []
  file_upload:
    image:
      detail: high
      enabled: true
      number_limits: 3
      transfer_methods:
      - remote_url
      - local_file
  model:
    completion_params:
      max_tokens: 501
      stop: []
    mode: chat
    name: command-r-plus
    provider: cohere
  more_like_this:
    enabled: false
  opening_statement: null
  pre_prompt: "Analyze the provided example, explaining how its functional and generative\
    \ grammars contribute to its pragmatic intention. Using a syntax tree, Generate\
    \ a variant of the example that uses part of speech tags instead of the literal\
    \ concepts\n<example>\n<input>\n<article_title> The Impact of Climate Change on\
    \ Coastal Cities </article_title>\n<article_outline> \n  1. Introduction\n  2.\
    \ Rising Sea Levels\n  3. Increased Storm Frequency\n  4. Conclusion\n</article_outline>\n\
    </input>\n<output>\n [\n    {\n      \"section\": \"Introduction\",\n      \"\
    bullets\": \"1. Overview of climate change effects on coastal cities 2. Importance\
    \ of understanding these impacts\"\n    },\n    {\n      \"section\": \"Rising\
    \ Sea Levels\",\n      \"bullets\": \"1. Causes of rising sea levels 2. Effects\
    \ on coastal infrastructure and communities3. Examples of affected cities\"\n\
    \    },\n   {\n      \"section\": \"Increased Storm Frequency\",\n      \"bullets\"\
    : \"1. Link between climate change and storm frequency 2. Impact of more frequent\
    \ and severe storms on coastal areas 3. Case studies of recent storms\"\n    },\
    \ \n   {\n      \"section\": \"Conclusion\",\n      \"bullets\": \"1. Summary\
    \ of key points 2. The urgency of addressing climate change 2. Call to action\
    \ for policymakers and communities\"\n    }\n  ]\n</output>\n</example>\n"
  prompt_type: simple
  retriever_resource:
    enabled: false
  sensitive_word_avoidance:
    configs: []
    enabled: false
    type: ''
  speech_to_text:
    enabled: false
  suggested_questions: []
  suggested_questions_after_answer:
    enabled: false
  text_to_speech:
    enabled: false
    language: ''
    voice: ''
  user_input_form: []
