app:
  description: 'Analyse the shit out your prompt and make it the paradigm game altering
    thing you''ve always wanted. '
  icon: "\U0001F916"
  icon_background: '#FFEAD5'
  mode: completion
  name: PromptCondenser
model_config:
  agent_mode:
    enabled: false
    max_iteration: 5
    strategy: function_call
    tools: []
  annotation_reply:
    enabled: false
  chat_prompt_config: {}
  completion_prompt_config: {}
  dataset_configs:
    datasets:
      datasets: []
    retrieval_model: single
  dataset_query_variable: ''
  external_data_tools: []
  file_upload:
    image:
      detail: high
      enabled: true
      number_limits: 3
      transfer_methods:
      - remote_url
      - local_file
  model:
    completion_params:
      stop: []
      temperature: 0.7
      top_k: 251
    mode: chat
    name: gemini-1.5-pro-latest
    provider: google
  more_like_this:
    enabled: true
  opening_statement: null
  pre_prompt: 'Analyze this Language Model Prompt:


    {{prompt_instruction_source}}


    Discourse and Function:

    Analyze the prompt''s discourse semantics, identifying relationships between its
    parts.Determine the intended communicative goal. Analyze the functional grammar,
    considering its pragmatic implications.

    Clarity and Structure:

    Identify potential ambiguities or clarity issues within the prompt and suggest
    corrections.Differentiate necessary details from extraneous ones.


    Condensation and Generation:

    Propose a method for condensing the prompt to its essential components.Write a
    condensed version of the prompt.Explain the generative grammar of your condensed
    version.'
  prompt_type: simple
  retriever_resource:
    enabled: false
  sensitive_word_avoidance:
    configs: []
    enabled: false
    type: ''
  speech_to_text:
    enabled: false
  suggested_questions: []
  suggested_questions_after_answer:
    enabled: false
  text_to_speech:
    enabled: false
    language: ''
    voice: ''
  user_input_form:
  - paragraph:
      default: ''
      label: prompt_instruction_source
      required: true
      variable: prompt_instruction_source
