app:
  description: Analyze the given selection from a structuralist/semiotic perspective,
    identifying and explaining the significance of its underlying structures and signifying
    systems. Your analysis should demonstrate a deep understanding of these concepts
    and offer insights into how they shape the meaning and interpretation of the selection.
  icon: "\U0001F916"
  icon_background: '#FFEAD5'
  mode: completion
  name: structuralist/semiotic perspective
model_config:
  agent_mode:
    enabled: false
    max_iteration: 5
    strategy: function_call
    tools: []
  annotation_reply:
    enabled: false
  chat_prompt_config: {}
  completion_prompt_config: {}
  dataset_configs:
    datasets:
      datasets: []
    retrieval_model: single
  dataset_query_variable: ''
  external_data_tools: []
  file_upload:
    image:
      detail: high
      enabled: false
      number_limits: 3
      transfer_methods:
      - remote_url
      - local_file
  model:
    completion_params:
      frequency_penalty: 0.6
      k: 500
      stop: []
      temperature: 0.4
    mode: chat
    name: command-r-plus
    provider: cohere
  more_like_this:
    enabled: false
  opening_statement: null
  pre_prompt: 'Analyze the given text from a structuralist/semiotic perspective, identifying
    and explaining the significance of its underlying structures and signifying systems.
    Your analysis should demonstrate a deep understanding of these concepts and offer
    insights into how they shape the meaning and interpretation of the selection.

    <text>

    {{input}}

    </text>'
  prompt_type: simple
  retriever_resource:
    enabled: false
  sensitive_word_avoidance:
    configs: []
    enabled: false
    type: ''
  speech_to_text:
    enabled: false
  suggested_questions: []
  suggested_questions_after_answer:
    enabled: false
  text_to_speech:
    enabled: false
    language: ''
    voice: ''
  user_input_form:
  - paragraph:
      default: ''
      label: Input
      required: false
      variable: input
