app:
  description: 'todo: convert to ruby methods

    <prompt> Generate a summary of the text:

    Here is a transcript text that needs to be formatted to improve readability:


    <transcript>

    {{TRANSCRIPT}}

    </transcript>


    Please perform the following steps to format this transcript:


    1. Add appropriate punctuation (periods, commas, question marks, exclamation points,
    etc.) and capitalization to the transcript text. Insert the punctuation marks
    in their correct locations and capitalize the first word of each sentence and
    any proper nouns.


    2. Split the punctuated text into paragraphs based on the content. Insert a blank
    line between each paragraph. Paragraphs should be divided based on topic, speaker,
    or at natural breaking points in the text. A paragraph should generally be 3-5
    sentences long.


    3. Check over the formatted text to make sure the punctuation, capitalization
    and paragraphs all look correct and enhance the readability of the transcript.


    Please return the formatted version of the transcript inside <formatted_transcript>
    tags.'
  icon: "\U0001F916"
  icon_background: '#FFEAD5'
  mode: completion
  name: Transcript - Improve Readability-v1
model_config:
  agent_mode:
    enabled: false
    max_iteration: 5
    strategy: function_call
    tools: []
  annotation_reply:
    enabled: false
  chat_prompt_config: {}
  completion_prompt_config: {}
  dataset_configs:
    datasets:
      datasets: []
    retrieval_model: single
  dataset_query_variable: ''
  external_data_tools: []
  file_upload:
    image:
      detail: high
      enabled: true
      number_limits: 3
      transfer_methods:
      - remote_url
      - local_file
  model:
    completion_params:
      stop: []
    mode: chat
    name: gemini-1.5-pro-latest
    provider: google
  more_like_this:
    enabled: false
  opening_statement: null
  pre_prompt: '<prompt> Generate a summary of the text:

    Here is a transcript text that needs to be formatted to improve readability:


    <transcript>

    {{TRANSCRIPT}}

    </transcript>


    Please perform the following steps to format this transcript:


    1. Add appropriate punctuation (periods, commas, question marks, exclamation points,
    etc.) and capitalization to the transcript text. Insert the punctuation marks
    in their correct locations and capitalize the first word of each sentence and
    any proper nouns.


    2. Split the punctuated text into paragraphs based on the content. Insert a blank
    line between each paragraph. Paragraphs should be divided based on topic, speaker,
    or at natural breaking points in the text. A paragraph should generally be 3-5
    sentences long.


    3. Check over the formatted text to make sure the punctuation, capitalization
    and paragraphs all look correct and enhance the readability of the transcript.


    Please return the formatted version of the transcript inside <formatted_transcript>
    tags.'
  prompt_type: simple
  retriever_resource:
    enabled: false
  sensitive_word_avoidance:
    configs: []
    enabled: false
    type: ''
  speech_to_text:
    enabled: false
  suggested_questions: []
  suggested_questions_after_answer:
    enabled: false
  text_to_speech:
    enabled: false
    language: ''
    voice: ''
  user_input_form:
  - paragraph:
      default: ''
      label: TRANSCRIPT
      required: true
      variable: TRANSCRIPT
